/**
 * UI/UX gate captures of "Add to my mod manager" for a mod with extra files (an expression set's table overlay and TweakXL file),
 * in the Expression sets panel, side by side with the Mod package panel's same flow. Light and dark, the panel at 300 and 480 px.
 *
 * Nothing real is touched: the tool starts its own authoring server with a throwaway data folder whose settings name a **fake**
 * game folder and a **fake** Mod Organizer 2 instance under the system temp folder (`XFS_MOD_INSTALL=on` so that isolated server
 * may place files, into the fakes only), opens a `?verify=1` workspace in a throwaway headless Chrome, and removes everything after.
 * A verification workspace's own install endpoint only plans (INSTALL-01), so the page's calls to it are routed to the isolated
 * server's endpoint (the page's `fetch`, wrapped by the tool); the plans, refusals and files placed are the real host's, against the fakes. Build results are
 * stand-ins the wrapped `fetch` answers (a real Build needs the game and WolvenKit): each names a prepared, hashed candidate in the project's
 * ignored `dist/` (`xfs-look-*`, removed afterwards), which the host verifies as it does any build. Viewports are masked.
 *
 *   bun tools/mod-manager-extras-look.ts <out dir> [port]
 */
import { createHash } from "node:crypto";
import { existsSync, mkdirSync, mkdtempSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { launch, MASK_VIEWPORTS, type Session } from "./cdp";
import { defaultLocalSettings } from "../src/local-settings";
import { EYE_MAKEUP_MOD } from "../src/mod-branding";

const [outArg, portArg = "4393"] = process.argv.slice(2);
if (!outArg) throw Error("Usage: bun tools/mod-manager-extras-look.ts <out dir> [port]");
const out = resolve(outArg), port = Number(portArg), base = `http://127.0.0.1:${port}`;
mkdirSync(out, { recursive: true });
const app = resolve(import.meta.dir, ".."), dist = resolve(app, "..", "dist");
const sha = (body: string) => createHash("sha256").update(body).digest("hex");

// ---- Fakes: a game folder, a Mod Organizer 2 instance with separators, and the server's own data folder ----
const temp = mkdtempSync(join(tmpdir(), "xfs-extras-look-"));
const game = join(temp, "Cyberpunk 2077"), mo2 = join(temp, "MO2"), data = join(temp, "data"), profile = "Main";
const MODLIST = ["# This file was automatically generated by Mod Organizer.", "+Neon Lashes", "+Looks_separator", "+Better Lighting",
  "+Visuals_separator", "+ArchiveXL", "+TweakXL", "+CORE, LIBS, FRAMEWORKS_separator"].join("\r\n") + "\r\n";
function resetFakes() {
  rmSync(game, { recursive: true, force: true }); rmSync(mo2, { recursive: true, force: true });
  rmSync(join(data, "install-receipts"), { recursive: true, force: true });
  mkdirSync(join(game, "bin", "x64"), { recursive: true }); mkdirSync(join(game, "archive", "pc", "mod"), { recursive: true });
  writeFileSync(join(game, "bin", "x64", "Cyberpunk2077.exe"), "stand-in");
  for (const mod of ["Neon Lashes", "Better Lighting", "ArchiveXL", "TweakXL"]) mkdirSync(join(mo2, "mods", mod), { recursive: true });
  mkdirSync(join(mo2, "profiles", profile), { recursive: true }); mkdirSync(join(mo2, "overwrite"), { recursive: true });
  writeFileSync(join(mo2, "profiles", profile, "modlist.txt"), MODLIST);
}
mkdirSync(data, { recursive: true });
resetFakes();
writeFileSync(join(data, "settings.json"), JSON.stringify({ ...defaultLocalSettings(), revision: 1, gameRoot: game, launchRoute: "mo2", mo2Root: mo2,
  mo2ProfileId: profile, installMode: "mo2" }, null, 2));

// ---- Prepared candidates (hashed, as Build promotes them) ----
type File = { path: string; body: string };
function candidate(id: string, manifest: Record<string, unknown>, files: File[]) {
  const folder = join(dist, id);
  rmSync(folder, { recursive: true, force: true });
  for (const file of files) { mkdirSync(join(folder, ...file.path.split("/").slice(0, -1)), { recursive: true }); writeFileSync(join(folder, ...file.path.split("/")), file.body); }
  writeFileSync(join(folder, "manifest.json"), JSON.stringify({ ...manifest, files: files.map(file => ({ path: file.path, sha256: sha(file.body), bytes: Buffer.byteLength(file.body) })),
    verifiedUnpackedFiles: files.length, installed: false, gameRenderingVerified: false }));
  return folder;
}
const EYE = "xfs_clook", SET = "xfs_mlook", NEWER = "xfs_mnewer";
const EYE_ID = "11111111-2222-4333-8444-000000000001";
candidate("xfs-look-eye", { schema: "xfs/local-package-2", productId: EYE_ID, modName: EYE_MAKEUP_MOD.modName, nameSource: "derived", archive: EYE,
  features: [{ feature: "eye-makeup", namespace: EYE }] }, [{ path: `archive/pc/mod/${EYE}.archive`, body: "eye archive" }, { path: `archive/pc/mod/${EYE}.archive.xl`, body: "eye xl" }]);
const setFiles = (archive: string) => [{ path: `archive/pc/mod/${archive}.archive`, body: `${archive} archive` }, { path: `archive/pc/mod/${archive}.archive.xl`, body: `${archive} xl` },
  { path: `archive/pc/mod/0${archive}_table.archive`, body: `${archive} table` }, { path: `r6/tweaks/${archive}/${archive}.yaml`, body: `${archive} records` }];

// ---- The server: isolated data, the fakes' settings, allowed to place files (into the fakes) ----
const server = Bun.spawn(["bun", "server.ts"], { cwd: app, env: { ...process.env, PORT: String(port), XFAS_DATA_DIR: data, XFS_SETTINGS_DIR: "", XFS_MOD_INSTALL: "on" },
  stdout: "ignore", stderr: "ignore" });
const report: Record<string, unknown> = { date: new Date().toISOString(), fakes: { game: "temp", mo2: "temp" }, captures: [] as string[] };
try {
  for (let i = 0; i < 160; i++) { try { if ((await fetch(`${base}/health`)).ok) break; } catch { /* booting */ } await Bun.sleep(250); }
  const api = `${base}/api/verification/part-presets`;
  const json = (method: string, body: unknown) => ({ method, headers: { "Content-Type": "application/json", Origin: base }, body: JSON.stringify(body) });
  const call = async <T>(url: string, init?: RequestInit): Promise<T> => { const r = await fetch(url, init); if (!r.ok) throw Error(`${url}: ${await r.text()}`); return r.json() as Promise<T>; };
  type Row = { id: string; name: string; revision: number };
  for (const set of await call<Row[]>(`${api}/sets?feature=expressions`)) await call(`${api}/sets/${set.id}?revision=${set.revision}`, { method: "DELETE", headers: { Origin: base } });
  for (const preset of await call<Row[]>(`${api}?feature=expressions`)) await call(`${api}/${preset.id}?revision=${preset.revision}`, { method: "DELETE", headers: { Origin: base } });
  const save = (name: string, controls: Record<string, number>) => call<Row>(api, json("POST", { feature: "expressions", name, part: { schema: "xfs/expression-part-1", body: { controls, links: {} } } }));
  const sly = await save("Sly smile", { lips_l_corner_up: 0.45, eye_r_brows_raise_out: 0.2 });
  const wide = await save("Wide-eyed", { eye_l_widen: 0.7, eye_r_widen: 0.7 });
  const smiles = await call<Row>(`${api}/sets`, json("POST", { feature: "expressions", name: "Smiles", members: [sly.id, wide.id] }));
  const newer = await call<Row>(`${api}/sets`, json("POST", { feature: "expressions", name: "Newer build", members: [sly.id] }));
  candidate("xfs-look-set", { schema: "xfs/local-package-2", productId: smiles.id, modName: "XF Expressions - Smiles", nameSource: "derived", archive: SET,
    features: [{ feature: "expressions", namespace: SET }] }, setFiles(SET));
  // A newer XF Studio's build: one more file, of a kind this version doesn't know where to put.
  candidate("xfs-look-newer", { schema: "xfs/local-package-2", productId: newer.id, modName: "XF Expressions - Newer build", nameSource: "derived", archive: NEWER,
    features: [{ feature: "expressions", namespace: NEWER }] }, [...setFiles(NEWER), { path: `r6/scripts/${NEWER}/${NEWER}.reds`, body: "script" }]);

  const setBuild = (productId: string, modName: string, archive: string, id: string, looks: Row[]) => ({ schema: "xfs/package-build-2", collectionId: productId,
    collectionSha256: "0".repeat(64), originalPresetCount: looks.length, omissions: [], requirements: {}, installed: false, gameRenderingVerified: false,
    products: [{ productId, modName, nameSource: "derived", archive, isDefault: true, omissions: [], requirements: {},
      features: [{ feature: "expressions", label: "Expressions", presets: looks.map(look => ({ id: look.id, revision: look.revision, label: look.name })), notes: [], omissions: [], experimental: [], details: {} }],
      package: join(dist, id), manifest: join(dist, id, "manifest.json"), verifiedUnpackedFiles: 4, installed: false, gameRenderingVerified: false }] });
  const eyeBuild = (look: { id: string; revision: number }) => ({ schema: "xfs/package-build-2", collectionId: "look", collectionSha256: "0".repeat(64), originalPresetCount: 1, omissions: [], requirements: {},
    installed: false, gameRenderingVerified: false,
    products: [{ productId: EYE_ID, modName: EYE_MAKEUP_MOD.modName, nameSource: "derived", archive: EYE, isDefault: true, omissions: [], requirements: {},
      features: [{ feature: "eye-makeup", label: "Eye makeup", selectorLabel: "XF", audience: "for a feminine and a masculine V", presets: [{ id: look.id, revision: look.revision, appearance: "xfs_eye_layer1__xfs_e01+000+matte", route: "flat" }], notes: [], omissions: [], experimental: [], packagedSha256: "a".repeat(64) }],
      package: join(dist, "xfs-look-eye"), manifest: join(dist, "xfs-look-eye", "manifest.json"), archiveSha256: "b".repeat(64), xlSha256: "c".repeat(64),
      verifiedUnpackedFiles: 2, installed: false, gameRenderingVerified: false }] });

  const tabs = (page: Session, title: string) => page.evaluate(`(() => { const t = [...document.querySelectorAll('[role=tab]')].find(t => [${JSON.stringify(title)}, ${JSON.stringify(title)} + "Early"].includes(t.textContent.trim())); t?.click(); return !!t; })()`);
  const sizeGroup = (page: Session, tab: string, width: number) => page.evaluate(`(() => { const t = [...document.querySelectorAll('[role=tab]')].find(t => [${JSON.stringify(tab)}, ${JSON.stringify(tab)} + "Early"].includes(t.textContent.trim()));
    const g = t?.closest('.dock-group'); if (!g) return false; g.style.width = "${width}px"; g.style.flex = "none"; g.style.maxWidth = "${width}px";
    // A group in a column takes its column's width: size the column too (the nearest ancestor laid out in a row).
    for (let e = g; e?.parentElement && e.parentElement !== document.body; e = e.parentElement)
      if (getComputedStyle(e.parentElement).flexDirection === "row") { if (e !== g) Object.assign(e.style, { width: "${width}px", flex: "none", maxWidth: "${width}px", minWidth: "${width}px" }); break; }
    return true; })()`);
  const click = (page: Session, selector: string, text: string) =>
    page.evaluate(`(() => { const b = [...document.querySelectorAll(${JSON.stringify(selector)})].find(e => e.textContent.trim().startsWith(${JSON.stringify(text)})); if (!b) throw Error("no " + ${JSON.stringify(text)}); b.click(); return true; })()`);
  const chooseSet = (page: Session, name: string) => page.evaluate(`[...document.querySelectorAll('.expr-sets ol[aria-label="Your expression sets"] .item-main')].find(b => b.textContent.includes(${JSON.stringify(name)}))?.click()`);
  async function groupShot(page: Session, selector: string, file: string) {
    const rect = await page.evaluate(`(() => { const g = document.querySelector(${JSON.stringify(selector)})?.closest('.dock-group'); if (!g) return null;
      const r = g.getBoundingClientRect(); return { x: Math.max(0, r.left), y: Math.max(0, r.top), width: r.width, height: Math.min(innerHeight - r.top, r.height) }; })()`);
    if (rect) { await page.screenshot(resolve(out, file), rect); (report.captures as string[]).push(file); }
  }
  /** The open sheet, with a margin. */
  async function sheetShot(page: Session, file: string) {
    const rect = await page.evaluate(`(() => { const d = [...document.querySelectorAll('dialog')].find(d => d.open); if (!d) return null; const r = d.getBoundingClientRect();
      return { x: Math.max(0, r.left - 12), y: Math.max(0, r.top - 12), width: r.width + 24, height: r.height + 24 }; })()`);
    if (rect) { await page.screenshot(resolve(out, file), rect); (report.captures as string[]).push(file); }
  }
  /** The success toast, captured on its own, then dismissed so it doesn't cover the panel's own capture. */
  async function toastShot(page: Session, file: string) {
    const rect = await page.evaluate(`(() => { const t = document.querySelector('.toasts'); if (!t || !t.childElementCount) return null; const r = t.getBoundingClientRect();
      return { x: Math.max(0, r.left - 8), y: Math.max(0, r.top - 8), width: r.width + 16, height: r.height + 16 }; })()`);
    if (rect) { await page.screenshot(resolve(out, file), rect); (report.captures as string[]).push(file); }
    await page.evaluate(`document.querySelectorAll('.toasts button[aria-label="Dismiss notification"]').forEach(b => b.click())`); await page.wait(400);
  }
  const sheetText = (page: Session) => page.evaluate(`[...document.querySelectorAll('dialog')].find(d => d.open)?.innerText ?? null`);
  const closeSheet = (page: Session) => page.evaluate(`(() => { const d = [...document.querySelectorAll('dialog')].find(d => d.open); [...(d?.querySelectorAll('button') ?? [])].find(b => b.textContent.trim() === 'Cancel')?.click(); return true; })()`);

  const passes = (["dark", "light"] as const).flatMap(scheme => ([300, 480] as const).map(width => ({ scheme, width })));
  for (const { scheme, width } of passes) {
    const tag = `${scheme}-${width}`;
    resetFakes();
    for (const folder of readdirSync(join(data))) if (folder.startsWith("verification-install")) rmSync(join(data, folder), { recursive: true, force: true });
    const page = await launch(`${base}/?verify=1`, { width: 1500, height: 1000, scheme });
    /** The page's next Build answer (a stand-in), and its install calls routed to the isolated server's endpoint (see the module note). */
    const route = `(() => { if (window.__lookRouted) return true; window.__lookRouted = true; const original = window.fetch.bind(window);
      window.fetch = (input, init) => { const url = typeof input === "string" ? input : input.url;
        if (url === "/api/verification/mod-install") return original("/api/mod-install", init);
        if (url === "/api/package" && init?.method === "POST" && window.__lookBuild) { const body = JSON.stringify(window.__lookBuild); window.__lookBuild = null;
          return Promise.resolve(new Response(body, { status: 200, headers: { "Content-Type": "application/json" } })); }
        return original(input, init); }; return true; })()`;
    const answerBuild = (result: unknown) => page.evaluate(`(${route}, window.__lookBuild = ${JSON.stringify(result)}, true)`);
    try {
      await page.waitFor("window.xfStudioShell && document.querySelector('.dock-group')", 120000);
      await page.evaluate(`(() => { document.querySelector('button[title="Skip tour"]')?.click(); window.xfStudioShell.runtime.modules.set("expressions", true); return true; })()`);
      await page.wait(500); await page.evaluate(MASK_VIEWPORTS);
      // The 3D preview's offer names the game folder detection found on this computer: dismissed, it stays out of the captures.
      await page.evaluate(`[...document.querySelectorAll('button')].find(b => b.textContent.trim() === 'Not now')?.click()`); await page.wait(200);

      // ---- Expression sets: build (stand-in result), the button, the plan with extras, success ----
      await tabs(page, "Expression sets");
      await page.waitFor("document.querySelector('.expr-sets')?.offsetParent", 20000);
      await sizeGroup(page, "Expression sets", width); await page.wait(600);
      await chooseSet(page, "Smiles"); await page.wait(300);
      await answerBuild(setBuild(smiles.id, "XF Expressions - Smiles", SET, "xfs-look-set", [sly, wide]));
      const built = await page.evaluate(`window.xfStudioShell.runtime.port.presets.execute({ kind: "partPresetSet.build", feature: "expressions", id: ${JSON.stringify(smiles.id)} })`);
      if (!built?.ok) throw Error(`Set build refused: ${JSON.stringify(built)} ${JSON.stringify(page.console.slice(-5))}`);
      await page.waitFor(`document.querySelector('.expr-sets .install-row')`, 20000); await page.wait(400);
      await page.evaluate(`document.querySelector('.expr-sets .install-row')?.scrollIntoView({ block: 'center' })`); await page.wait(200);
      await groupShot(page, ".expr-sets", `${tag}-sets-01-built.png`);
      await click(page, ".expr-sets .install-row button", "Add to");
      await page.waitFor(`[...document.querySelectorAll('dialog')].find(d => d.open)?.innerText.includes('Nothing else in your mod list changes')`, 20000)
        .catch(async error => { await page.screenshot(resolve(out, `${tag}-debug.png`)); throw Error(`${error.message}: ${await sheetText(page)}`); });
      await page.wait(300);
      await sheetShot(page, `${tag}-sets-02-plan-with-extras.png`);
      report[`${tag}-sets-plan`] = await sheetText(page);
      await page.evaluate(`[...[...document.querySelectorAll('dialog')].find(d => d.open).querySelectorAll('button')].find(b => b.textContent.trim() === 'Add to Mod Organizer 2').click()`);
      await page.waitFor(`document.querySelector('.expr-sets .install-line.done')`, 20000); await page.wait(300);
      await toastShot(page, `${tag}-sets-03b-added-toast.png`);
      await groupShot(page, ".expr-sets", `${tag}-sets-03-added.png`);
      report[`${tag}-sets-added`] = await page.evaluate(`document.querySelector('.expr-sets .install-line').innerText`);
      report[`${tag}-placed`] = existsSync(join(mo2, "mods", "XF Expressions - Smiles", "r6", "tweaks", SET, `${SET}.yaml`));
      // ---- The unknown-kind refusal ----
      await chooseSet(page, "Newer build"); await page.wait(300);
      await answerBuild(setBuild(newer.id, "XF Expressions - Newer build", NEWER, "xfs-look-newer", [sly]));
      await page.evaluate(`window.xfStudioShell.runtime.port.presets.execute({ kind: "partPresetSet.build", feature: "expressions", id: ${JSON.stringify(newer.id)} })`);
      await page.waitFor(`document.querySelector('.expr-sets .result-card')?.innerText.includes('Newer build')`, 20000); await page.wait(400);
      await page.evaluate(`[...document.querySelectorAll('.expr-sets .install-row')].at(-1)?.scrollIntoView({ block: 'center' })`);
      await page.evaluate(`[...[...document.querySelectorAll('.expr-sets .result-card .install-row button')]].find(b => b.textContent.trim().startsWith('Add to')).click()`);
      await page.waitFor(`[...document.querySelectorAll('dialog')].find(d => d.open)?.querySelector('.install-status')?.textContent`, 20000); await page.wait(300);
      await sheetShot(page, `${tag}-sets-04-unknown-kind.png`);
      report[`${tag}-sets-unknown`] = await sheetText(page);
      await closeSheet(page); await page.wait(300);
      if (await page.evaluate(`!![...document.querySelectorAll('dialog')].find(d => d.open)`)) { await page.key("Escape"); await page.wait(300); }
      await page.waitFor(`![...document.querySelectorAll('dialog')].find(d => d.open)`, 5000);

      // ---- The Mod package panel's same flow, at the same width ----
      // Floated, so the panel is seen at the pass's width whatever column it docks in.
      await page.evaluate(`window.xfStudioShell.dock.float("package")`); await page.wait(400);
      await tabs(page, "Mod package"); await page.wait(300); await sizeGroup(page, "Mod package", width);
      await page.evaluate(`(() => { const g = [...document.querySelectorAll('[role=tab]')].find(t => t.textContent.trim() === "Mod package")?.closest('.dock-group');
        const w = g?.parentElement?.closest('[class*="float"]') ?? g; if (w) { w.style.width = "${width}px"; w.style.height = "900px"; } return true; })()`);
      await page.wait(500);
      await answerBuild(eyeBuild(await page.evaluate(`(() => { const p = window.xfStudioShell.runtime.port.library.summary().draft.presets[0]; return { id: p.id, revision: p.revision ?? 1 }; })()`)));
      await page.evaluate(`window.xfStudioShell.runtime.request({ kind: "package", action: "build" }, { quietSuccess: true })`);
      await page.waitFor(`document.querySelector('.package-result:not(.expr-sets *) .install-row')`, 20000); await page.wait(400);
      await page.evaluate(`document.querySelector('.package-result:not(.expr-sets *) .install-row')?.scrollIntoView({ block: 'center' })`); await page.wait(200);
      await groupShot(page, ".package-result:not(.expr-sets *)", `${tag}-package-01-built.png`);
      await click(page, ".package-result:not(.expr-sets *) .install-row button", "Add to");
      await page.waitFor(`[...document.querySelectorAll('dialog')].find(d => d.open)?.innerText.includes('Nothing else in your mod list changes')`, 20000)
        .catch(async error => { await page.screenshot(resolve(out, `${tag}-debug.png`)); throw Error(`${error.message}: ${await sheetText(page)}`); });
      await page.wait(300);
      await sheetShot(page, `${tag}-package-02-plan.png`);
      await page.evaluate(`[...[...document.querySelectorAll('dialog')].find(d => d.open).querySelectorAll('button')].find(b => b.textContent.trim() === 'Add to Mod Organizer 2').click()`);
      await page.waitFor(`document.querySelector('.package-result:not(.expr-sets *) .install-line.done')`, 20000); await page.wait(300);
      await toastShot(page, `${tag}-package-03b-added-toast.png`);
      await groupShot(page, ".package-result:not(.expr-sets *)", `${tag}-package-03-added.png`);
      report[`${tag}-console`] = page.console.filter(entry => entry.type === "exception" || entry.type === "error");
    } finally { await page.close(); }
  }

  // Comparison sheets: each Expression sets state beside the Mod package panel's same step, at the same width.
  const pairs: [string, string, string][] = [["After Build: Add and Show in folder", "sets-01-built", "package-01-built"],
    ["The plan (a mod with extra files; a plain archive and .xl)", "sets-02-plan-with-extras", "package-02-plan"],
    ["Added", "sets-03-added", "package-03-added"], ["Added: the toast", "sets-03b-added-toast", "package-03b-added-toast"], ["A file of an unknown kind (refused; Mod package has no such build: its plan shown for the sheet pattern)", "sets-04-unknown-kind", "package-02-plan"]];
  const tags = passes.map(pass => `${pass.scheme}-${pass.width}`);
  for (const tag of tags) writeFileSync(resolve(out, `compare-${tag}.html`), `<!doctype html><meta charset=utf-8><style>body{font:13px system-ui;background:#888;margin:12px}section{display:flex;gap:16px;align-items:flex-start;margin-bottom:24px}figure{margin:0}figcaption{font-weight:600;margin-bottom:4px}img{border:1px solid #444}</style><h1>${tag}</h1>` +
    pairs.map(([title, own, pattern]) => `<h2>${title}</h2><section><figure><figcaption>Expression sets</figcaption><img src="${tag}-${own}.png"></figure><figure><figcaption>Mod package</figcaption><img src="${tag}-${pattern}.png"></figure></section>`).join(""));
  const viewer = await launch("about:blank", { width: 1400, height: 1000 });
  try {
    for (const tag of tags) {
      await viewer.send("Page.navigate", { url: `file:///${resolve(out, `compare-${tag}.html`).replaceAll("\\", "/")}` }); await viewer.wait(1200);
      const height = await viewer.evaluate(`document.documentElement.scrollHeight`);
      await viewer.viewport(1400, Math.min(height, 14000)); await viewer.wait(400);
      await viewer.screenshot(resolve(out, `compare-${tag}.png`));
    }
  } finally { await viewer.close(); }
} finally {
  server.kill();
  await Bun.sleep(500);
  for (const id of ["xfs-look-eye", "xfs-look-set", "xfs-look-newer"]) rmSync(join(dist, id), { recursive: true, force: true });
  rmSync(temp, { recursive: true, force: true });
  writeFileSync(resolve(out, "report.json"), JSON.stringify(report, null, 2));
}
console.log(JSON.stringify({ captures: (report.captures as string[]).length }));
