import {expect,test} from "bun:test";
import * as THREE from "three";
import {installProceduralGlintStudy} from "../tools/glitter-glint-study";

test("UV-cell glint pilot chains existing shader ownership and restores it",()=>{
  const material=new THREE.MeshPhysicalMaterial({opacity:.4});
  let priorCalls=0;
  const prior:typeof material.onBeforeCompile=shader=>{priorCalls++;shader.vertexShader+="\n// existing skin hook";};
  const priorKey=()=>"existing-skin-key";
  material.onBeforeCompile=prior;material.customProgramCacheKey=priorKey;
  const study=installProceduralGlintStudy(material);
  const shader={vertexShader:THREE.ShaderLib.physical.vertexShader,
    fragmentShader:THREE.ShaderLib.physical.fragmentShader,uniforms:{}} as Parameters<typeof material.onBeforeCompile>[0];
  material.onBeforeCompile(shader,{} as THREE.WebGLRenderer);
  expect(priorCalls).toBe(1);
  expect(shader.vertexShader).toContain("// existing skin hook");
  expect(shader.fragmentShader).toContain("directionalLights[ xfsLight ].direction");
  expect(shader.fragmentShader).toContain("dFdx( uv )");
  expect(shader.fragmentShader).toContain("transpose( xfsGlintTbn )");
  expect(shader.fragmentShader).toContain("xfsGlintPolygonDistance");
  expect(shader.fragmentShader).toContain("signedCells");
  expect(shader.fragmentShader).toContain("linear height ramp drawn on each");
  expect(shader.fragmentShader).toContain("vec2( cos( rampAngle ), sin( rampAngle ) )");
  expect(shader.fragmentShader).toContain("float distanceUv = length( uv - centre )");
  expect(shader.fragmentShader).toContain("xfsGlintUnit( cell, 14u ) >= xfsGlintDensity");
  expect(shader.fragmentShader).toContain("min( bodyCoverage, 1.0 )");
  expect(shader.fragmentShader).toContain("max( 20.0, xfsGlintPower * 0.35 ) : xfsGlintPower");
  expect(shader.fragmentShader).not.toContain("gl_FragCoord");
  expect(shader.fragmentShader).not.toContain("transpose( tbn )");
  expect(shader.fragmentShader).toContain("#include <opaque_fragment>");
  expect(material.customProgramCacheKey()).toStartWith("existing-skin-key|");
  expect(material.opacity).toBe(.4);
  study.setEnabled(true);study.setStrength(0);study.setPower(1200);
  expect(shader.uniforms.xfsGlintShape?.value).toBe(0);
  expect(shader.uniforms.xfsGlintSeed?.value).toBe(0);
  expect(shader.uniforms.xfsGlintDensity?.value).toBe(.9);
  expect(shader.uniforms.xfsGlintFineShare?.value).toBe(.65);
  study.setShape("polygon");study.setSeed(173);
  expect(shader.uniforms.xfsGlintShape?.value).toBe(1);
  expect(shader.uniforms.xfsGlintSeed?.value).toBe(173);
  study.setDensity(.65);
  expect(shader.uniforms.xfsGlintDensity?.value).toBe(.65);
  study.setFineShare(.82);
  expect(shader.uniforms.xfsGlintFineShare?.value).toBe(.82);
  study.setShape("circle");study.setSeed(0);
  expect(shader.uniforms.xfsGlintShape?.value).toBe(0);
  expect(shader.uniforms.xfsGlintSeed?.value).toBe(0);
  expect(()=>study.setStrength(NaN)).toThrow();
  expect(()=>study.setPower(0)).toThrow();
  expect(()=>study.setSeed(-1)).toThrow();
  expect(()=>study.setSeed(1.5)).toThrow();
  expect(()=>study.setSeed(65536)).toThrow();
  expect(()=>study.setDensity(-.1)).toThrow();
  expect(()=>study.setDensity(1.1)).toThrow();
  expect(()=>study.setDensity(NaN)).toThrow();
  expect(()=>study.setFineShare(-.01)).toThrow();
  expect(()=>study.setFineShare(Number.NaN)).toThrow();
  expect(()=>study.setShape("star" as "circle")).toThrow();
  study.dispose();
  expect(material.onBeforeCompile).toBe(prior);
  expect(material.customProgramCacheKey).toBe(priorKey);
  expect(()=>study.setEnabled(true)).toThrow();
  material.dispose();
});
