/**
 * Static site build: bun tools/build.ts [outDir]
 * Pages in src/pages/*.html start with a <!--page {json}--> header and are wrapped in src/layout.html.
 * The Knowledge section (knowledge/) is generated from the repository's knowledge/*.md pages through the templates in
 * src/knowledge/ (tools/knowledge.ts). Placeholders are {{name}}; an unknown placeholder fails the build. No dependencies, no network.
 */
import { createHash } from "node:crypto";
import { mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { basename, dirname, join, relative, resolve } from "node:path";
import { basePath, formatDate, loadConfig, repoRoot, siteRoot, styleGuideSource, type SiteConfig } from "./config";
import { escapeHtml } from "./html";
import { caveatHtml, legendHtml, loadKnowledge, maturityTag, type Knowledge, type KnowledgeOptions } from "./knowledge";
import { releaseVars } from "./release";

export { escapeHtml };
export type PageMeta = {
  title: string;
  description: string;
  /** Nav item id marked aria-current="page". */
  nav?: string;
  /** Use base-path absolute links (needed by 404.html, which Pages serves at any depth). */
  absoluteLinks?: boolean;
  noindex?: boolean;
  bodyClass?: string;
};
export type BuildResult = { outDir: string; pages: string[]; files: string[]; config: SiteConfig; knowledge: Knowledge };
export type BuildOptions = { outDir?: string; baseUrl?: string; knowledge?: Partial<KnowledgeOptions> }
  & Pick<Parameters<typeof loadConfig>[0] & {}, "releaseStatus" | "release">;

const PAGE_HEADER = /^<!--page\s+(\{[\s\S]*?\})\s*-->[ \t]*\r?\n?/;

export function fill(template: string, vars: Record<string, string>, source: string) {
  return template.replace(/\{\{(\w+)\}\}/g, (_, name: string) => {
    if (!(name in vars)) throw Error(`${source}: unknown placeholder {{${name}}}`);
    return vars[name];
  });
}

export function parsePage(text: string, source: string): { meta: PageMeta; body: string } {
  const match = PAGE_HEADER.exec(text);
  if (!match) throw Error(`${source}: missing <!--page {...}--> header`);
  const meta = JSON.parse(match[1]) as PageMeta;
  if (!meta.title?.trim() || !meta.description?.trim()) throw Error(`${source}: page header needs title and description`);
  return { meta, body: text.slice(match[0].length) };
}

const sha = (bytes: Uint8Array) => createHash("sha256").update(bytes).digest("hex");

export function buildSite(options: BuildOptions = {}): BuildResult {
  const config = loadConfig({ baseUrl: options.baseUrl, releaseStatus: options.releaseStatus, release: options.release });
  const release = releaseVars(config);
  const outDir = resolve(options.outDir ?? join(siteRoot, "dist"));
  const base = basePath(config);
  // The guide is generated by the Studio UI build. Read it before clearing dist so a
  // missing source fails the build without leaving behind an apparently complete site.
  const styleGuide = readFileSync(styleGuideSource);
  // Likewise generate the knowledge pages first: a refused link or personal data fails before dist is touched.
  const knowledge = loadKnowledge({ repoRoot, repoUrl: config.repoUrl, repoBranch: config.repoBranch, ...options.knowledge });
  rmSync(outDir, { recursive: true, force: true });
  mkdirSync(join(outDir, "assets"), { recursive: true });

  const files: string[] = [];
  const versions: Record<string, string> = {};
  const assetDir = join(siteRoot, "src", "assets");
  for (const name of readdirSync(assetDir).sort()) {
    const bytes = readFileSync(join(assetDir, name));
    writeFileSync(join(outDir, "assets", name), bytes);
    versions[name] = sha(bytes).slice(0, 10);
    files.push(`assets/${name}`);
  }
  writeFileSync(join(outDir, "style-guide.html"), styleGuide);
  files.push("style-guide.html");

  const layout = readFileSync(join(siteRoot, "src", "layout.html"), "utf8");
  const blob = `${config.repoUrl}/blob/${config.repoBranch}`;
  const pages: string[] = [];
  const sitemap: string[] = [];

  /** Renders one page into the layout. `path` is the output path, e.g. "credits.html" or "knowledge/index.html". */
  const renderPage = (path: string, source: string, meta: PageMeta, body: string, extra: Record<string, string> = {}) => {
    const depth = path.split("/").length - 1;
    const root = meta.absoluteLinks ? base : "../".repeat(depth);
    const home = meta.absoluteLinks ? base : depth ? root : "./";
    const link = (href: string) => /^[a-z]+:/i.test(href) ? href
      : meta.absoluteLinks ? (href.startsWith("./") ? base + href.slice(2) : base + href)
      : depth ? (href.startsWith("./") ? root + href.slice(2) : root + href) : href;
    const shared: Record<string, string> = {
      root, home, siteName: escapeHtml(config.siteName),
      repo: config.repoUrl, blob, tree: `${config.repoUrl}/tree/${config.repoBranch}`,
      authorName: escapeHtml(config.author.name), authorUrl: config.author.url,
      statusReviewed: formatDate(config.statusReviewed), statusReviewedIso: config.statusReviewed,
      releaseStatement: release.releaseStatement, downloadSection: release.downloadSection,
      releaseSummary: escapeHtml(release.releaseSummary),
      ...extra,
    };
    const content = fill(body, shared, source).trim();
    const urlPath = path === "index.html" ? "" : path.endsWith("/index.html") ? path.slice(0, -"index.html".length) : path;
    const pageUrl = `${config.baseUrl}${urlPath}`;
    const nav = config.nav.map(item =>
      `<li><a href="${link(item.href)}"${item.id === meta.nav ? ' aria-current="page"' : ""}>${escapeHtml(item.label)}</a></li>`).join("");
    const html = fill(layout, {
      ...shared,
      title: escapeHtml(fill(meta.title, extra, `${source} title`)),
      description: escapeHtml(fill(meta.description, { releaseSummary: release.releaseSummary, ...extra }, `${source} description`)),
      robots: meta.noindex ? '<meta name="robots" content="noindex">\n' : "",
      canonical: meta.noindex ? "" : `<link rel="canonical" href="${pageUrl}">\n`,
      ogUrl: meta.noindex ? "" : `<meta property="og:url" content="${pageUrl}">\n`,
      bodyClass: escapeHtml(meta.bodyClass ?? `page-${path.replace(/\.html$/, "").replace(/\//g, "-")}`),
      css: `${root}assets/site.css?v=${versions["site.css"]}`,
      js: `${root}assets/theme.js?v=${versions["theme.js"]}`,
      nav, content,
    }, "src/layout.html");
    mkdirSync(join(outDir, dirname(path)), { recursive: true });
    writeFileSync(join(outDir, path), html);
    pages.push(path); files.push(path);
    if (!meta.noindex) sitemap.push(`  <url><loc>${pageUrl}</loc></url>`);
  };

  const pageDir = join(siteRoot, "src", "pages");
  for (const file of readdirSync(pageDir).filter(name => name.endsWith(".html")).sort()) {
    const source = relative(siteRoot, join(pageDir, file)).replaceAll("\\", "/");
    const { meta, body } = parsePage(readFileSync(join(pageDir, file), "utf8"), source);
    renderPage(`${basename(file, ".html")}.html`, source, meta, body);
  }
  renderKnowledge(knowledge, config, renderPage);

  writeFileSync(join(outDir, "sitemap.xml"),
    `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${sitemap.join("\n")}\n</urlset>\n`);
  files.push("sitemap.xml");
  return { outDir, pages: pages.sort(), files: files.sort(), config, knowledge };
}

type RenderPage = (path: string, source: string, meta: PageMeta, body: string, extra?: Record<string, string>) => void;

/** knowledge/index.html plus one page per published knowledge topic. */
function renderKnowledge(knowledge: Knowledge, config: SiteConfig, renderPage: RenderPage) {
  const templateDir = join(siteRoot, "src", "knowledge");
  const read = (name: string) => parsePage(readFileSync(join(templateDir, name), "utf8"), `src/knowledge/${name}`);
  const issueUrl = (title: string, pageUrl: string, file: string) => `${config.repoUrl}/issues/new?${new URLSearchParams({
    title: `Knowledge: ${title}`,
    body: `Page: ${pageUrl}\nSource: ${file}\n\nWhat is wrong or missing, and how do you know? Links to sources, captures or tests help most.\n`,
  })}`;
  const legend = legendHtml(knowledge.grades);
  const updated = (iso: string | null) => iso
    ? `Last updated <time datetime="${iso}">${formatDate(iso)}</time>`
    : "Last updated: not yet committed";

  const indexIssue = issueUrl("knowledge base", `${config.baseUrl}knowledge/`, "knowledge/README.md");
  const topics = knowledge.pages.map(page => `      <li class="kb-topic">
        <h3><a href="${page.slug}.html">${page.titleHtml}</a></h3>
        <p>${page.topic.summaryHtml}</p>
        <p class="kb-topic-meta">${maturityTag(page.topic)}${page.topic.maturityNote ? `<span>${escapeHtml(page.topic.maturityNote)}</span>` : ""}<span>${updated(page.updated)}</span></p>
      </li>`).join("\n");
  const unpublished = knowledge.topics.filter(topic => !knowledge.pages.some(page => page.slug === topic.slug));
  const planned = unpublished.length ? `    <div class="kb-planned">
      <h3>Not published yet</h3>
      <p>Topics the knowledge base covers only as pointers to existing research so far.</p>
      <ul>
${unpublished.map(topic => `        <li>${topic.summaryHtml} ${maturityTag(topic)}</li>`).join("\n")}
      </ul>
    </div>` : "";
  const index = read("index.html");
  renderPage("knowledge/index.html", "src/knowledge/index.html", index.meta, index.body, {
    caveat: caveatHtml(indexIssue), legend, topics, planned, issueUrl: escapeHtml(indexIssue),
  });

  const template = read("page.html");
  for (const page of knowledge.pages) {
    const pageUrl = `${config.baseUrl}knowledge/${page.slug}.html`;
    const file = `knowledge/${page.file}`;
    const issue = issueUrl(page.title, pageUrl, file);
    const edit = `${config.repoUrl}/edit/${config.repoBranch}/${file}`;
    const toc = page.headings.filter(heading => heading.level === 2)
      .map(heading => `        <li><a href="#${heading.id}">${heading.html.replace(/<a\b[^>]*>|<\/a>/g, "")}</a></li>`).join("\n");
    renderPage(`knowledge/${page.slug}.html`, file, template.meta, template.body, {
      pageTitle: page.title,
      pageTitleHtml: page.titleHtml,
      pageDescription: `XF Studio research notes: ${page.topic.summaryText}`,
      maturityTag: maturityTag(page.topic),
      updated: updated(page.updated),
      sourceUrl: `${config.repoUrl}/blob/${config.repoBranch}/${file}`,
      editUrl: edit, issueUrl: escapeHtml(issue), file: escapeHtml(page.file),
      caveat: caveatHtml(issue, edit), legend, toc, article: page.html,
    });
  }
}

if (import.meta.main) {
  const result = buildSite({ outDir: process.argv[2] });
  for (const skip of result.knowledge.skipped) console.log(`Knowledge page ${skip.slug} not published (${skip.reason}).`);
  console.log(`Built ${result.pages.length} pages (${result.knowledge.pages.length} knowledge), ${result.files.length} files for ${result.config.baseUrl} → ${relative(process.cwd(), result.outDir) || "."}`);
}
