/**
 * Composition guidance completing each pattern's What/When: how it combines with
 * neighbours, how it adapts to narrow or spacious workspaces, and what drives it.
 * `pattern()` merges these for any field the pattern itself does not set.
 */
export const GUIDANCE: Record<string, { combine?: string; adapt?: string; drives?: string }> = {
  "f-type": { combine: "Display caps label a region (tab, eyebrow, badge); the body face explains it directly beneath; mono values align in the same column across rows.",
    drives: "Tokens --font-display, --font-ui, --font-mono and the --fs-* scale in studio.css." },
  "f-space": { combine: "Sections stack with --sp-6; controls inside a section with --sp-4; a toolbar row keeps --sp-2 between related buttons.",
    drives: "Tokens --sp-*, --control-h, --row-h, --tab-h, --header-h, --status-h." },
  "f-shape": { combine: "A bevelled surface never nests inside another bevelled surface of the same size; cards inside panels are bevelled, the panel group is not.",
    drives: "corner-shape: bevel with --bevel / --bevel-sm radii; --shadow only for layers above the dock." },
  "f-icons": { combine: "Icons lead labels in buttons, tabs and menus; menus reserve a 16 px icon column so labels align even without an icon.",
    adapt: "In condensed tab strips and compact header actions the icon stands alone while the label remains the accessible name.",
    drives: "src/studio-ui/icons.ts (icon(), iconMarkup()); the guide's grid is generated from the same table." },
  "f-motion": { combine: "Progress bars sit directly under the action that started the work; readiness badges repeat the state where the result is seen (stage and status bar).",
    adapt: "Motion is identical at every size; reduced-motion users get instant state changes.", drives: "--dur, --ease and the sweep/pulse keyframes; readiness phase from previewReadiness." },
  "f-focus": { combine: "Focus follows the action: after closing a menu or popover it returns to the invoker; after a reorder it stays on the moved row.",
    adapt: "Identical in both themes and all sizes; the ring colour switches from yellow (dark) to ink (light) for ≥3:1 against adjacent colours.", drives: "--focus token; roving tabindex in tab strips, rows and menus." },
  "s-category": { adapt: "Compact headers show only the icon and chevron; the menu content is the same.",
    drives: "Static today; a future category registry would supply entries with their own panel registries and actions." },
  "s-status": { combine: "The message slot mirrors the newest Activity entry; readiness mirrors the Head badge; errors also toast so they are not missed." },
  "s-palette": { adapt: "Width is capped to the window minus 32 px; results scroll; it works identically in compact workspaces where header labels are icons." },
  "s-sheet": { combine: "Opened from View preferences, the Panels menu, the palette or the ? key; never stacked on another dialog.", adapt: "Width is capped to the window; the body scrolls and the definition list wraps.",
    drives: "bindingReference() from src/input-bindings.ts, the same catalogue as r-keys in this guide; preferences inputHints.set." },
  "d-split": { combine: "Splits hold groups or further splits; a group's minimum size stops a splitter before content collapses.",
    adapt: "Sizes are fractions, so resizing the window scales every column and row proportionally.", drives: "DockTree split nodes (axis, sizes) via setSizes()." },
  "d-float": { drives: "DockTree.floating windows (x, y, w, h, node) via applyDrop({kind:'float'}), setWindowRect(), raiseWindow() and recoverWindows()." },
  "d-composite": { adapt: "A composite keeps its members' proportions when resized; if a member leaves, the window returns that member's share.",
    drives: "A floating window whose node is a split; created by applyDrop with a split target on a floating group." },
  "d-feedback": { adapt: "Guides are fixed-size (34 px) at any workspace size; edge guides stay reachable in compact layouts; previews are computed from the actual target rectangle." },
  "d-sandbox": { combine: "Pairs with d-feedback: the static specimen explains the vocabulary, the sandbox lets you test it.",
    adapt: "Fixed 360 px area; resolution uses real measured rectangles.", drives: "resolveDrop() and previewRect() from src/studio-ui/dock/snap.ts." },
  "d-max": { combine: "The maximized group keeps its tab strip and a Restore button; floating windows stay above it.",
    adapt: "Most useful in compact windows for the Head or UV map.", drives: "DockTree.maximized via setMaximized()." },
  "d-keyboard": { combine: "The same items appear from the tab's context menu, the group ⋯ button and (for Float/Go to) the command palette.",
    adapt: "Lists every open group, docked or floating, so it scales with any arrangement.", drives: "DockView.panelMenuItems() calling applyDrop() with the same targets a drag would resolve." },
  "d-sizes": { combine: "A new panel names its shell slot in its view contribution, which places it in both size classes; missing panels rejoin their default siblings on restore.",
    drives: "defaultWide(), defaultCompact(), COMPACT_BREAKPOINT and DockState {wide, compact}." },
  "d-persist": { combine: "Theme preference is stored beside the layout; both change without touching recipes, Undo or the library.",
    adapt: "Each size class is recovered against the current window, so a layout saved on a large monitor opens safely on a laptop." },
  "d-live": { combine: "Menus, drags and splitters behave exactly as in the Studio.", adapt: "Fixed-size demo area.", drives: "DockView from src/studio-ui/dock/dock-view.ts with sample panels." },
  "c-buttons": { adapt: "Header actions collapse to icon-only buttons below 1100 px; panel buttons wrap onto new rows rather than shrinking." },
  "c-chips": { combine: "The library chip sits beside the preset name in the header and under the collection name in Presets; result badges sit in the result card's head.",
    adapt: "Chips hide below 720 px in the header only; the Presets panel keeps them.", drives: "libraryState() from library.summary(); result badges from files.snapshot().package." },
  "c-fields": { combine: "A field is always paired with a visible label or an accessible name; inline rename replaces the row's button in place.",
    adapt: "Fields fill their column; titles truncate with an ellipsis rather than wrapping.", drives: "collection.rename, preset.edit rename, layer.edit rename; application validation decides." },
  "c-slider": { combine: "Pair related sliders in one row only when both fit (Colour + Opacity); disabled sliders keep their reason directly beneath.",
    adapt: "Sliders fill their column; readouts never wrap." },
  "c-switch": { combine: "Switches stack in a section with their notes; a switch that unlocks a slider sits directly above it (Smooth point gradients → Point blend).",
    adapt: "Full-width rows in every size class.", drives: "Recipe switches: control transactions (pigment/softness) or dispatch (layer.setSymmetry); preview switches: preview.* actions." },
  "c-segmented": { combine: "The selected choice's explanation appears as a note beneath (e.g. handle modes).",
    adapt: "Segments keep their labels; the group wraps within its panel rather than scrolling." },
  "c-color": { combine: "Sits beside Opacity in the Pigment section; finish-specific facet colours reuse the same control.",
    adapt: "Fixed-width swatch and hex field.", drives: "layer.setColor and glitter.setIrregular/setDirect color via control transactions." },
  "c-finish": { adapt: "Tiles reflow from three columns to one; the export line wraps under the tiles." },
  "c-rows": { adapt: "In narrow lists (<250 px) the meta column hides; names truncate; trailing actions appear on hover, focus or selection only." },
  "c-context": { adapt: "Menus reposition to stay inside the window and flip above or left of the anchor near edges; long reasons wrap inside a 340 px maximum width." },
  "c-popover": { combine: "Replaces the menu that opened it, anchored to the same point.", adapt: "Fixed 280 px width, repositioned inside the window." },
  "c-confirm": { combine: "Anchored to the button that triggered it; the alternative safe action is offered beside the risky one.",
    adapt: "Same as context menus.", drives: "files.capability for each offered action (package.build, package.check)." },
  "c-toasts": { adapt: "Stack bottom-right above the status bar, at most four; width caps to the window on small screens.",
    drives: "Outcomes from dispatch(), files.execute() and library.execute(); adapter messages from status.message." },
  "c-progress": { combine: "A progress bar sits directly under the button that started the work; the status bar repeats the message.",
    adapt: "Bars fill their container; badges never wrap." },
  "c-empty": { combine: "Replaces the list or result it stands for, in the same place, with the action that would fill it.",
    adapt: "Fills the panel width.", drives: "Absence in library.summary(), editor.recipe(), files.snapshot().package or previewState().savedV." },
  "c-result": { combine: "Pairs with the Layers panel (warning flags) and the finish export line, which use the same wording.",
    adapt: "Lists wrap; hashes break anywhere; long paths wrap in monospace." },
  "c-facts": { combine: "Sits under the action that produced the facts (Load V from a save).",
    adapt: "Single column in every size.", drives: "previewState().savedV.result (applied) and status.assets.characterDetails (skin, face details, eyes, brows, lashes, hair, piercings and body of the shown V)." },
  "c-activity": { combine: "Receives every toast and quieter records (cancelled pickers, routine successes); the status bar shows the latest entry.",
    adapt: "Single column; the newest 80 entries are shown.", drives: "Presentation-only Feedback log (not persisted)." },
  "c-history": { combine: "A tab beside Layers. The header's Undo, Redo and History buttons and Ctrl+Z / Ctrl+Shift+Z move the same current marker one step at a time; the palette names the step (“Redo: Move point”).",
    adapt: "Times hide below 230 px of panel width; labels truncate, never wrap. The current step scrolls into view after every change.",
    drives: "authoring.historyTimeline() (steps with stable ids, labels, times, current index, redo count, trimmed flag) and one history.jumpTo {entryId} action, refused while a gesture or slider adjustment is open." },
  "c-strip": { combine: "Sticks to the top of the inspector while its content scrolls.", adapt: "Name truncates; the position text stays.",
    drives: "editor.layer() and editor.recipe()." },
  "c-viewport": { combine: "The Head panel's tools duplicate the most frequent Camera & light and Motion toggles; the full controls stay in those panels.",
    adapt: "Hint discovery hides below 720 px; the UV canvas fills any panel shape, and Fit fits the shape to it." },
  "c-handles": { combine: "Selecting a handle updates the Shape, Pigment & edge and Warp inspectors.",
    adapt: "Handle sizes are fixed in screen pixels; zoom the UV map or the camera for precision." },
  "t-saved": { adapt: "Header chip hides below 720 px; the Presets panel and status bar keep the information." },
  "t-undo": { adapt: "The same wording in toasts, menus and the palette at every size.",
    drives: "history.undo capability; preset.edit restore; collection.recover; views never enter the look history." },
  "t-async": { combine: "Collection edits pause (disabled with a reason) while a library request runs; layer editing continues during a save.",
    adapt: "Progress lives in the panel that started it and in the status bar." },
  "t-disabled": { combine: "The same reason text appears in every entry point for the same action.", adapt: "Reasons wrap under controls; they are never truncated." },
  "t-errors": { combine: "An error toast and an Activity entry for every failure; the panel that started the request keeps its last error until the next attempt.",
    adapt: "Toasts cap their width; the Activity log keeps the full text.", drives: "{ ok:false, code, message } outcomes; conflict and stale_result codes add recovery actions." },
  "t-stale": { combine: "Stale results keep their content and add a warning note with the next step.", adapt: "The badge wraps under the title in narrow panels." },
  "t-gesture": { combine: "Panel moves cancel an active viewport gesture first so a layout change never commits a half-finished edit.",
    adapt: "Identical in every layout." },
  "k-editing": { drives: "Every surface listed in r-actions; all edits go through dispatch, control transactions or gesture sessions." },
  "k-library": { adapt: "In compact layouts Library shares a tab group with Layers and Presets; toasts carry the recovery actions regardless.",
    drives: "library.summary(), library.execute(open/save/saveCopy/refresh), files.execute(collection.recover/import/export/plan)." },
  "k-package": { adapt: "In compact layouts Mod package is a tab next to Layers so omissions and their layers are one tab apart.",
    drives: "files.execute(package.check/build), files.snapshot().package, finishCatalogue()." },
  "k-compact": { combine: "Head, UV map and one inspector remain visible together; everything else is one tab away.",
    adapt: "At 640 px the head cell narrows but stays portrait and visible; maximize it (double-click its tab bar) for close judgement, or float a panel when two inspectors are needed at once.", drives: "defaultCompact() and the compact DockTree." },
  "k-future": { adapt: "Follows the same wide/compact defaults as eye makeup.",
    drives: "Would need a category registry, the category's own typed actions and catalogue entries, and discussion with the maintainer first." },
  "x-history": { combine: "Library panel below Saved collections; opening a revision uses the same recoverable-draft rules as Open.", adapt: "Timeline collapses to the latest five with “Show all”." },
  "x-gallery": { combine: "A view toggle on the Presets panel; selection and rename behave as in rows.", adapt: "Grid columns follow panel width; list view below 260 px." },
  "x-palette": { combine: "Opens from the colour field's swatch; picking applies layer.setColor as one Undo step.", adapt: "Grid reflows to panel width." },
  "x-contours": { combine: "Inside Shape above the point navigator; selecting a contour scopes point commands.", adapt: "Uses ordered rows at every size." },
  "x-compare": { combine: "Docks beside Head; shares camera state optionally.", adapt: "Stacks vertically in compact layouts." },
  "x-provenance": { combine: "Extends Character's fact list with per-asset rows.", adapt: "Single column." },
  "x-bulk": { combine: "Adds a selection count to list heads and batch commands to row menus.", adapt: "Keyboard Shift/Ctrl selection at every size." },
  "x-release": { combine: "A section of Mod package beneath the result card.", adapt: "Checklist rows wrap." },
  "r-panels": { combine: "Titles, icons and purposes come from the view contributions (views/) for the app, menus, palette and this table.", adapt: "Table scrolls horizontally in narrow windows.",
    drives: "The view contributions (views/): PANEL_IDS and PANEL_META derive from them." },
  "r-actions": { combine: "Use with the capability inventory and action catalogue in research/authoring.", adapt: "Table scrolls horizontally in narrow windows.",
    drives: "StudioPresentationPort." },
  "r-keys": { combine: "Generated from the same catalogue as the ? Keyboard & mouse dialog, viewport hints, menu and palette shortcut labels.", adapt: "Two columns at every size.",
    drives: "src/input-bindings.ts, resolved by the shell keydown handler, DockView tabs, ItemList rows, viewport panels and both gesture adapters." },
};
