import { code, esc } from "./kit";

/**
 * The component library's catalogue (research/authoring/ui-component-library.md): one entry per component that panels and feature
 * views compose, with its full contract. The style guide's "Component library" section is generated from it, each entry with a live
 * specimen built by the production component (library-demo.ts), and tests/ui-component-library.test.ts checks that every export of
 * src/studio-ui/components has an entry here.
 */
export type LibraryCategory = "General" | "Layout" | "Feature-specific";
export type LibraryEntry = {
  id: string; title: string; category: LibraryCategory;
  /** The module (under src/studio-ui) and the exports this entry documents. */
  module: string; exports: readonly string[];
  what: string; anatomy: string; variants: string; states: string; sizes: string;
  when: string; combine: string; adapt: string; drives: string; a11y: string; do: string; avoid: string;
  /** Other style-guide patterns that show it in context. */
  see?: readonly string[];
};

export const LIBRARY: readonly LibraryEntry[] = [
  { id: "lib-button", title: "Button", category: "General", module: "controls.ts", exports: ["button", "applyCapability"],
    what: "A command with a verb label and an optional icon: the default control for doing something.",
    anatomy: "Bevelled box · optional leading icon · label (a <code>span</code>) · nothing else. Icon-only drops the label and keeps it as the accessible name and tooltip.",
    variants: "default, <code>primary</code> (one per region), <code>quiet</code>, <code>ghost</code> (tool clusters), <code>danger</code>; <code>small</code>; <code>iconOnly</code>; <code>menu</code> (opens a menu: <code>aria-haspopup</code>).",
    states: "rest, hover, active, focus-visible, pressed (<code>aria-pressed</code> for a tool toggle), unavailable (the main-action pattern: <code>aria-disabled</code> with its reason).",
    sizes: "28 px (<code>--control-h</code>), small 24 px (<code>--control-h-sm</code>); icon-only is square.",
    when: "Any action in panel content, headers, sheets and toasts.",
    combine: `A row of actions: ${code("h(\"div\", { class: \"row wrap gap-s\" }, button({ label: \"Check\", icon: \"check\", onClick }), button({ label: \"Build\", variant: \"primary\", onClick }))")}. A toast's actions and a sheet's footer are buttons too.`,
    adapt: "Labels never wrap; a crowded header shows icon-only buttons with the label as tooltip and name.",
    drives: `Availability is the action's capability: ${code("applyCapability(control, capability)")}.`,
    a11y: "Native button; Enter and Space. An unavailable one stays focusable, says why (its description and the page's reason tip) and runs nothing when pressed.",
    do: "Start the label with a verb; use one primary per region; mark menu triggers with <code>menu</code>.",
    avoid: "Building <code>h(\"button\", { class: \"btn\" })</code> by hand (it skips the unavailable guard); native <code>disabled</code> on a main action; two primaries side by side.",
    see: ["c-buttons"] },
  { id: "lib-icon-button", title: "Icon button", category: "General", module: "components/icon-button.ts", exports: ["iconButton"],
    what: "A borderless square button for a surface's chrome: panel header actions, a sheet's or toast's close, a row's visibility or more-actions mark.",
    anatomy: "24 px square (22 px small) · one 16 px icon · no border until hover.",
    variants: "<code>small</code>; <code>menu</code> (<code>aria-haspopup</code>); <code>pressed</code> (a toggle, coloured signal when on); <code>mode</code> (with <code>pressed</code>: a mode such as mirrored sides, tinted as well when on, so it reads at a glance); <code>expanded</code> (a disclosure); <code>className</code> for placement hooks.",
    states: "rest (muted), hover, focus-visible, pressed, unavailable (the main-action pattern, faded).",
    sizes: "24 px; small 22 px. It never shrinks inside a header (the panel header keeps its actions whole).",
    when: "Chrome around content. Inside panel content, among bordered buttons, use <code>button({ iconOnly })</code> so it matches them.",
    combine: `A sheet's head: ${code("h(\"div\", { class: \"sheet-head\" }, h(\"h2\", {}, title), iconButton({ label: \"Close\", icon: \"close\", onClick: close }))")}.`,
    adapt: "Fixed size at every width.",
    drives: "The owner's intent (close, open a menu, toggle); availability via <code>applyCapability</code>.",
    a11y: "Named by <code>label</code>, titled by it too unless <code>title</code> says more; menu triggers announce their popup; toggles announce their state.",
    do: "Give every icon button a label that names the action and its object (\"Hide Petal wash\"). Use <code>mode</code> for a mode the person turns on for a region, not for per-row marks that are on by default.",
    avoid: "Hand-built <code>.icon-btn</code> elements; an icon button without a tooltip.", see: ["d-group"] },
  { id: "lib-switch", title: "Switch", category: "General", module: "controls.ts", exports: ["Toggle"],
    what: "An on/off setting that takes effect at once.",
    anatomy: "Track and thumb · label to its right · optional help tip beside it · reserved note line when it can carry a reason.",
    variants: "with or without <code>help</code>; <code>reserveNote</code>.",
    states: "off, on, focus-visible, disabled (a form field: native disabled with its reason on the note line or in the tooltip).; mixed (<code>update(false, { mixed: true })</code>: a switch over several things of which some are on shows its thumb halfway and reads \"mixed\", announced as a checkbox since ARIA's switch has no mixed value; a press turns it fully on)",
    sizes: "30 × 16 px track; row height 24 px.",
    when: "Settings and visibility toggles that apply immediately (Show my V's own makeup).",
    combine: "Stack switches in a section; one per line.", adapt: "The label wraps; the track stays at its start.",
    drives: "An application action on change; its state from a read-only snapshot.",
    a11y: "<code>input type=checkbox role=switch</code> with a label; Space toggles; the reason is its description.",
    do: "Name the setting, not the action (\"Show my V's own makeup\").", avoid: "Raw checkboxes; a switch that needs a Save button.", see: ["c-switch"] },
  { id: "lib-slider", title: "Slider", category: "General", module: "controls.ts", exports: ["Slider", "bindRangeTransaction", "fillRange", "NoteLine"],
    what: "A continuous value with a live readout; one Undo step per drag or keyboard burst.",
    anatomy: "Label (with help tip) and readout on one line · range track with its signal fill · reserved note line.",
    variants: "<code>reserveNote</code> for a limit that comes and goes; <code>help</code>.",
    states: "rest, dragging (a transaction is open), cancelled (Escape restores the start), disabled with its reason.",
    sizes: "Full width of its column; track 4 px, thumb 12 × 16 px.",
    when: "Values judged by eye (opacity, softness).",
    combine: "Beside a colour field in a two-column form row; under a section title.",
    adapt: "Full width; the readout stays right-aligned.",
    drives: "A begin/edit/commit/cancel transaction the application groups into one Undo step.",
    a11y: "Labelled range; arrows, Page Up/Down, Home/End; Escape during a drag restores the starting value.",
    do: "Format the readout in the person's terms (\"85%\").", avoid: "A number box beside a plain slider: use Slider with value.", see: ["c-slider"] },
  { id: "lib-slider-value", title: "Slider with value", category: "General", module: "components/slider-with-value.ts", exports: ["SliderWithValue"],
    what: "A slider whose one readout is also where its exact value is typed, with an optional reset: one readout per value, never a second number box.",
    anatomy: "Label (with help tip) · the readout (typed into in place) · reset, shown only while the value is set · range under them · a note line only when asked for. Inline: a short label, the range, the readout and reset on one line (a pair's sides).",
    variants: "<code>reset</code> with <code>defaultValue</code>; <code>inline</code> with <code>accessibleLabel</code>; <code>reserveNote</code>; <code>update(value, { text })</code> for a readout the owner words itself (a pair's \"14 / 10 %\", shown muted).",
    states: "default; <em>set</em> (away from its default: the label emphasised with a signal mark, the reset shown); dragging; typing an exact value; the owner's readout; disabled (its reason on the note line when reserved, else in the tooltip and description).",
    sizes: "Label line 22 px; track as Slider; about 44 px a control stacked, 22 px inline, so a list of them stays dense at 300 px.",
    when: "Values people also type, with a meaningful default (expression and shape values).",
    combine: "Rows of them inside a Group section; two inline ones make a Pair control's separate state. A list of them shares one disabled reason, said once by the panel.",
    adapt: "Full width; the label truncates with an ellipsis before the readout or reset would move.",
    drives: "The Slider's transaction for drags; a typed value, Delete or the reset is one begin/edit/commit step, clamped and snapped to the step.",
    a11y: "The range is labelled by the visible label (or <code>accessibleLabel</code>) and speaks the formatted value; one tab stop: Enter types an exact value in the readout's place (Enter commits, Escape reverts, focus returns to the range), Delete or Backspace returns to the default; the field is named \"&lt;label&gt;, exact value\"; the reset is \"Reset &lt;label&gt;\".",
    do: "Give it the default so people can see what they changed.", avoid: "A number box beside the slider; a reserved note line under every row of a list; a faded reset on every row." },
  { id: "lib-pair", title: "Pair control", category: "General", module: "components/pair-control.ts", exports: ["PairControl"],
    what: "A left/right pair of values (a brow's two sides, two eyelids), edited together or apart. Whether it is linked is the owner's state, decided in a group heading's mirror toggle or a whole-panel switch, never by a toggle on every pair.",
    anatomy: "Linked: one Slider with value under the pair's name. Separate: the pair's name, then one inline line per side (\"L\", \"R\": range, readout, reset).",
    variants: "side labels and names (<code>sideLabels</code>, <code>sideNames</code>); every Slider with value option.",
    states: "linked; uneven (linked while the sides differ: the one readout says both values, muted, \"14 / 10 %\", and the next edit sets both); separate; disabled.",
    sizes: "Linked about 44 px; separate about 70 px.",
    when: "Symmetric features edited together by default (brows, lids).",
    combine: "Inside a Group section whose heading holds the region's mirror toggle (an icon button with <code>mode</code>).",
    adapt: "Rows stack vertically at every width.",
    drives: "Edits carry <code>{ sides: \"both\" | \"left\" | \"right\", value }</code>; <code>update(values, { linked, disabled, reason })</code>.",
    a11y: "Linked, the range is named \"&lt;label&gt;, both sides\"; separate, the sides are a group named by the pair with ranges named \"&lt;label&gt;, left\" and \"&lt;label&gt;, right\".",
    do: "Default to linked; show uneven sides in the readout, not a note.", avoid: "Repeating the pair's name in its row (\"Brow height\" over \"Brow height, both sides\"); a link toggle or pill under every pair." },
  { id: "lib-bipolar", title: "Bipolar slider", category: "General", module: "components/bipolar-slider.ts", exports: ["BipolarSlider"],
    what: "One value between two opposite directions with a resting centre, for a movement that goes one way or the other but never both (look left or right, brow up or down).",
    anatomy: "Label (with help tip) and one readout that names the direction (\"0\", \"20 % right\") · reset, shown only away from the centre · range with a centre mark, filled from the centre to the thumb · the two direction words, small, at the track's ends · note line only on request.",
    variants: "<code>unit</code>; <code>format</code> for other readouts; <code>detent</code>; <code>reset: false</code>; <code>reserveNote</code>; asymmetric ranges (the centre mark sits at 0 wherever that falls).",
    states: "at the centre; <em>set</em> (away from it: the label emphasised with a signal mark); <em>mixed</em> (the data sets both directions: the readout says Mixed, the thumb has a dashed edge at the net value, nothing changes until the next edit replaces both with one value); dragging; typing an exact value; disabled with its reason.",
    sizes: "Label line 22 px; track as Slider; direction words <code>--fs-2xs</code>. About 50 px a control, so a list of them stays dense at 300 px.",
    when: "Opposing controls merged into one value (gaze sideways and up/down, brow up/down, jaw left/right). A value that only grows from zero is a Slider with value.",
    combine: `Rows inside a Group section, like Slider with value: ${code("new BipolarSlider({ label: \"Look sideways\", min: -100, max: 100, step: 1, unit: \"%\", ends: { negative: \"Left\", positive: \"Right\" }, transaction })")}. Name the axis in the label and the directions at the ends; never put both directions in the label.`,
    adapt: "Full width; the label truncates with an ellipsis before the readout or reset would move; the direction words stay at the ends.",
    drives: "The Slider's begin/edit/commit/cancel transaction for drags and keys; a typed value, Delete, a double-click or the reset is one begin/edit/commit step, clamped and snapped. <code>update(value, { mixed, disabled, reason })</code> from the owner's snapshot.",
    a11y: "A native range labelled by the visible label; its value text is the readout's words (\"20 % right\", \"Mixed: 20 % right\"); the direction words are decoration. One tab stop: Enter types an exact value in the readout's place (Enter commits, Escape reverts, focus returns to the slider), Delete or Backspace returns to the centre, arrows and Home/End as any range; the reset is \"Reset &lt;label&gt;\".",
    do: "Snap to the centre on a drag so rest is easy to hit; show which way in words, not only by position.", avoid: "Two sliders for directions that can't both happen (\"Look in\" and \"Look out\"); a signed number without its direction word.", see: ["lib-slider-value"] },
  { id: "lib-light-list", title: "Light list", category: "Feature-specific", module: "components/light-list.ts", exports: ["LightList"],
    what: "A lighting setup's lights as an ordered list, one compact row each, for choosing the light the editor below shows.",
    anatomy: "The Ordered list's row (grip · lead · name and meta · trailing) with a colour chip (the layer swatch) and a glyph for the light's kind (a sun for directional, the lighting mark for spot) in the lead, the light's name, and one muted line of what matters at a glance (\"40 · shadows\": strength and shadows; the glyph shows the kind).",
    variants: "None beyond the Ordered list's; the kind glyph follows the light.",
    states: "rest, hover, selected (signal fill with the inset edge), dragging, renaming in place, disabled (the whole list, with the editor's reason).",
    sizes: "Rows 32 px (<code>--row-h</code>); chip 16 px; the meta line hides below 250 px of container width.",
    when: "The lights of the shown lighting setup in Camera &amp; light. Other ordered collections use the Ordered list itself.",
    combine: `Above the light editor, with an Add light button under it: ${code("new LightList({ label: \"Lights\", onSelect, onMove, onRename, onDelete, onDuplicate, onMenu, maxLength: 60 })")}; the owner keeps the selection and passes it to <code>update(items, selected)</code>.`,
    adapt: "Full width; names truncate before the chip or grip would move; the meta line goes first when narrow.",
    drives: "Intents only (select, move, rename, delete, duplicate, menu); the owner dispatches the setup actions and feeds rows from the setup's read model.",
    a11y: "The Ordered list's keyboard: arrows move focus, Alt+Up/Down reorder, F2 renames, Delete removes, the menu key opens the row menu. Each row is named \"&lt;name&gt;, &lt;kind&gt; light, &lt;meta&gt;\", so the chip and glyph never carry meaning alone.",
    do: "Keep the meta line short and parallel across rows (strength, shadows): the name has priority and the meta gives way first.", avoid: "A colour or glyph as the only way to tell lights apart; hand-built rows.", see: ["lib-item-list", "lib-direction-dial"] },
  { id: "lib-direction-dial", title: "Direction dial", category: "Feature-specific", module: "components/direction-dial.ts",
    exports: ["DirectionDial", "dialPoint", "dialDirection", "azimuthWords"],
    what: "Where a light sits around V, seen from above: one handle whose angle round the dial is the light's direction and whose distance from the centre is its height.",
    anatomy: "Label line with two readouts (the angle, the height), each typed into in place · a round dial: V's head at the centre with her nose toward the bottom edge (\"Front\"), \"Behind\" at the top, \"V's right\" on the left and \"V's left\" on the right as when you face her, a dashed ring for level with the head, the edge for straight below · the handle in the light's colour · the setup's other lights as small faint dots · note line only on request.",
    variants: "<code>elevation</code> range (default −89° to 89°); <code>reserveNote</code>; <code>others</code> dots on or off.",
    states: "rest; dragging (a transaction is open; Escape restores the start); typing an exact angle or height; focus-visible (the dial's ring); unavailable with its reason on the note line (no handle movement, readouts not editable).",
    sizes: "Dial up to 208 px wide (the dial and its four direction words), shrinking to its column; label line 22 px; handle 11 px.",
    when: "A light's direction in the lighting setup editor. A single angle alone is a Slider with value.",
    combine: `Under the Light list's selected light, above its strength and cone sliders: ${code("new DirectionDial({ label: \"Direction\", transaction })")}, then <code>update({ azimuth, elevation }, { colour, others })</code>.`,
    adapt: "Keeps its aspect; centred in narrow columns; the readouts stay on the label line.",
    drives: "A begin/edit/commit/cancel transaction of <code>{ azimuth, elevation }</code> in degrees: a drag or a keyboard burst is one transaction, a typed value one step. The owner turns it into the light's placement about the head.",
    a11y: "One tab stop, <code>role=slider</code> with the angle as its value and \"330°, from the front, V's left, 20° up\" as its value text. Left and Right turn by 5°, Page Up and Page Down by 15°, Up and Down raise and lower by 5°, Home brings it to the front, Enter types the angle; the readouts are named \"&lt;label&gt; angle, exact value\" and \"&lt;label&gt; height, exact value\".",
    do: "Show the light's own colour on the handle and its neighbours as dots, so the rig reads at a glance.", avoid: "Raw x, y, z fields for a light's position; two unrelated sliders for angle and height.", see: ["lib-light-list", "lib-slider-value"] },
  { id: "lib-segmented", title: "Segmented control", category: "General", module: "controls.ts", exports: ["Segmented"],
    what: "One choice among two to four short options, all visible in one strip.",
    anatomy: "Label · sunken frame · segments (icon and/or label) · the chosen one raised with a signal underline · with <code>reserveNote</code>, a note line under them.",
    variants: "<code>compact</code>; <code>showLabel: false</code> (named by its group label); <code>reserveNote</code>.",
    states: "chosen (<code>aria-pressed</code>), hover, unavailable option (with its reason), the whole group unavailable (one reason in the note line), a transient note (\"Loading that idle\") in the reserved line.",
    sizes: "24 px segments inside a 28 px frame.", when: "Modes, views and sizes (Both eyes / Single eye; Nodes / Mod data; 512 / 1K / 2K / 4K). A varying or longer set, long labels or a numbered set use the Choice list.",
    combine: "In a page header's actions, a toolbar or a panel section, with its note line above the controls that depend on it.", adapt: "The strip never wraps: drop labels to icons before it would, or use a Choice list.",
    drives: "An action per choice; the chosen value from a snapshot; <code>setOptions(choices)</code> when the list changes (rebuilt only when it differs, focus kept on the same choice).", a11y: "A labelled group of toggle buttons; a disabled group states its reason in the note line and as the group's description.",
    do: "Keep options short and parallel.", avoid: "A strip with more than four options or long labels (use the Choice list), or lists that need search.", see: ["c-segmented", "c-choice-list"] },
  { id: "lib-choice-list", title: "Choice list", category: "General", module: "components/choice-list.ts", exports: ["ChoiceList", "choiceItem", "attachSwatchCard", "swatchCard"],
    what: "One choice among more than about four options or long labels, all shown at once, in the Character panel's choice look (its creator choices are built from the same <code>choiceItem</code>).",
    anatomy: "Label with optional help tip · choices (bordered, the chosen one with the signal border, fill and underline; optional swatch; optional group headings) · reserved note line.",
    variants: "<code>layout</code>: <code>chips</code> (wrap as chips, the default), <code>rows</code> (one full-width row each, for long labels), <code>tiles</code> (an even grid for numbered sets); options with <code>group</code> headings, a <code>swatch</code>, or a short visible label with an accessible <code>name</code> (tile \"3\" is \"Eye shape 3\"); <code>swatchCard</code> (resting on or focusing a choice with a swatch shows the swatch card, lib-swatch-card, and the list can show the contrast-enhanced marker beside its label).",
    states: "chosen (<code>aria-selected</code>), hover, focus, an unavailable choice (focusable, its reason as a tip), the whole list unavailable (one reason in the note line), a passing note.",
    sizes: "28 px choices (24 px content) with 4 px gaps; tiles at least 36 px wide.",
    when: "Motion › Body, Character › Clothes in the 3D view (rows) and Eye shape (tiles), Settings › Head used for the eye plate (rows), the Glitter preview model (rows). Two to four short options: Segmented.",
    combine: "In a panel section, label above, note line below, dependent controls after the note.",
    adapt: "Chips and tiles wrap as the panel narrows; rows wrap their labels, never truncate them.",
    drives: "<code>setOptions(choices)</code> (a no-op when unchanged; focus kept on the same choice), <code>update(selected, capability, { disabled, reason, note, enhanced })</code>; <code>onSelect(value)</code>. Any list of <code>choiceItem</code>s gets the swatch card with <code>attachSwatchCard(list, item => sample)</code> (the page's one card, <code>swatchCard()</code>).",
    a11y: "The listbox pattern: one Tab stop (the chosen choice), arrows, Home and End move focus without choosing (Up and Down by a row in tiles), Enter, Space or a click chooses; unavailable choices keep focus and say why.",
    do: "Use <code>rows</code> when a label is longer than a few words, <code>tiles</code> for numbers.", avoid: "A dropdown for a handful of choices; Segmented with more than four options.", see: ["c-choice-list"] },
  { id: "lib-color", title: "Colour field", category: "General", module: "controls.ts", exports: ["ColorField"],
    what: "A colour with a native picker and a hex entry.", anatomy: "Label · swatch frame (the picker) · hex box.",
    variants: "none.", states: "picking (a transaction), invalid hex (red border, restored), disabled.", sizes: "Swatch 34 × 28 px; hex 88 px.",
    when: "Pigment colours.", combine: "Beside an opacity slider.", adapt: "Fixed width.",
    drives: "A transaction: one Undo step per pick or hex entry.", a11y: "Both inputs named; Enter applies the hex.",
    do: "Show the hex in lower case.", avoid: "Colour without a text alternative.", see: ["c-color"] },
  { id: "lib-select", title: "Select field", category: "General", module: "controls.ts", exports: ["SelectField"],
    what: "A choice from a short list that doesn't need filtering.", anatomy: "Label (with help tip) · native select · chevron.",
    variants: "with <code>help</code>.", states: "rest, focus, disabled with its reason, unavailable options.", sizes: "28 px; full width.",
    when: "Up to about fifteen options.", combine: "In forms, one per line.", adapt: "Full width.",
    drives: "An action on change; options from a snapshot.", a11y: "Native select with its label.",
    do: "Use the Combobox once the list needs searching or grouping.", avoid: "Hand-copied select markup without the wrapper and chevron.", see: ["c-fields"] },
  { id: "lib-combobox", title: "Combobox", category: "General", module: "components/combobox.ts", exports: ["Combobox"],
    what: "A select for long, grouped lists the person can type into to filter.",
    anatomy: "Label · text input with a chevron · floating listbox with group headings, options (label and optional detail) and an empty line.",
    variants: "groups with or without headings; options with detail text; unavailable options with a reason.",
    states: "closed (shows the chosen label), open and filtered, active option, nothing matches, disabled.",
    sizes: "28 px field; list up to 320 px tall, the field's width.",
    when: "Lists of dozens to hundreds (a Start-from picker with saved and installed expressions).",
    combine: "At the top of a feature panel, above its Group sections.",
    adapt: "The list floats over what follows, so opening it never moves the layout.",
    drives: "<code>onChange(value)</code>; the groups from a snapshot.",
    a11y: "The ARIA combobox pattern: <code>role=combobox</code>, <code>aria-expanded</code>, <code>aria-controls</code>, <code>aria-activedescendant</code>; a listbox of named groups and options; Down or Alt+Down opens, Up and Down move (skipping unavailable), Ctrl+Home and Ctrl+End jump, Enter chooses, Escape restores.",
    do: "Group by where the options come from.", avoid: "Loading a long list into a native select." },
  { id: "lib-search", title: "Search field", category: "General", module: "components/search-field.ts", exports: ["SearchField"],
    what: "Filters a list as the person types.",
    anatomy: "Search icon · input · clear button (kept in place, shown only with a query) · the list's no-matches state.",
    variants: "<code>debounce</code> (raise it for an expensive filter rather than filtering on change only).",
    states: "empty, typing (filter after a short pause), query shown, no matches.", sizes: "28 px; full width.",
    when: "Above any list long enough to scan (help topics, creator options, world objects).",
    combine: `${code("const search = new SearchField({ label: \"Search expressions\", onFilter })")} above the list; when nothing matches show ${code("search.noMatches(\"expressions\")")}.`,
    adapt: "Full width; the clear button never changes its width.",
    drives: "<code>onFilter(query)</code> with the trimmed query.",
    a11y: "<code>role=search</code> landmark and input named by <code>label</code>; Enter filters at once; Escape clears (Escape on an empty field is left to the page).",
    do: "Say what the search covers in its placeholder.", avoid: "Some searches filtering as you type and others only on Enter." },
  { id: "lib-expander", title: "Expander", category: "General", module: "expander.ts", exports: ["expander", "expanderLabel", "setExpanded", "isExpanded", "ExpandAll"],
    what: "One disclosure button for everything that folds, at five levels.",
    anatomy: "Chevron (right when folded, down when open) · label · optional count.",
    variants: "levels <code>group</code>, <code>section</code>, <code>subsection</code>, <code>row</code>, <code>maker</code>; Expand all / Collapse all.",
    states: "folded, open, hover, focus-visible.", sizes: "10 px chevron; type by level.",
    when: "Hierarchies people scan and open selectively.", combine: "Wrapped in a heading element to keep the heading's level; the Group section adds a count and reset.",
    adapt: "Labels clamp to one line.", drives: "Presentation state only.",
    a11y: "The WAI disclosure pattern (<code>aria-expanded</code>, <code>aria-controls</code>).",
    do: "Keep what is above the button still when it folds.", avoid: "Native <code>details</code> with the browser's marker.", see: ["c-expanders"] },
  { id: "lib-group-section", title: "Group section", category: "General", module: "components/group-section.ts", exports: ["GroupSection", "resetGroupSections"],
    what: "A foldable group of controls with a count of what is set, the group's own actions and a group reset.",
    anatomy: "Heading row: expander (chevron, title, \"N set\" in plain muted mono) · optional help tip · the group's actions (<code>actions</code>: a region's mirror toggle) · reset, shown only while something is set · body.",
    variants: "any expander level; <code>heading</code> 3–5; with or without reset, help and actions.",
    states: "folded, open, forced open by a search, hidden by a search; the reset out of sight (its place kept) while nothing is set or editing is unavailable.",
    sizes: "Body indented by the chevron's width.",
    when: "Panels with many groups of controls (a face's expression regions).",
    combine: "A Search field above; Slider with value, Pair control and Bipolar slider rows inside.",
    adapt: "The heading row never wraps its actions; the title clamps.",
    drives: "<code>update({ set, forceOpen, hidden, disabled })</code> from the feature's snapshot and search; <code>onReset</code> dispatches the group's reset.",
    a11y: "Disclosure pattern; the actions and reset sit outside the expander button, so pressing them never folds the group; the count is part of the button's name.",
    do: "Keep the open state per session (its key).", avoid: "A tinted badge for the count (it isn't a status); resetting from inside the expander button." },
  { id: "lib-help-tip", title: "Help tip", category: "General", module: "help-tip.ts", exports: ["helpTip", "setHelp", "installHelpTips"],
    what: "What a heading, row or control is, in a rich tooltip on a small help icon beside it.",
    anatomy: "18 px circled help icon · one page-wide bubble (optional title, short paragraphs).",
    variants: "with a title.", states: "hover, focus (shown), pinned by a click, empty (hidden, keeps its place).", sizes: "18 px.",
    when: "Explanations the person doesn't need to act on.", combine: "Beside labels and section titles, outside the label.",
    adapt: "The bubble flips above when there's no room below.", drives: "Static text.",
    a11y: "A real button named \"About &lt;what&gt;\" whose text is its description; Escape closes.",
    do: "Keep it to what something is.", avoid: "Inline notes that only explain.", see: ["c-help-tips"] },
  { id: "lib-reason-tip", title: "Reason tip", category: "General", module: "reason-tip.ts", exports: ["installReasonTips"],
    what: "Why an unavailable main action is unavailable, on focus, hover or a press.",
    anatomy: "One page-wide tip with a warning edge.", variants: "none.", states: "shown, lingering after a press.", sizes: "Up to 320 px wide.",
    when: "Automatic for every control marked by <code>applyCapability</code>.", combine: "With any button or icon button.",
    adapt: "Flips above when needed.", drives: "The capability's reason.", a11y: "The same reason is the control's accessible description.",
    do: "Write reasons as the next step.", avoid: "\"Unavailable\" without a why.", see: ["c-buttons"] },
  { id: "lib-menu", title: "Menu, value and confirm popovers", category: "General", module: "menu.ts", exports: ["openMenu", "closeMenus", "menuFromSections", "openValuePopover", "openConfirmPopover"],
    what: "Context and overflow menus whose entries carry their own capability; a small anchored editor for one value; an anchored question before an action that can't be undone.",
    anatomy: "Entries (icon, label, hint or reason, shortcut, submenu chevron) · headings · separators. Value popover: title, field, note, optional option switches, Cancel and Apply. Confirm popover: title, one sentence of what happens, Cancel and the action's verb.",
    variants: "checkable entries, danger entries, submenus; a planned entry (<code>tag: \"Soon\"</code> with <code>quietReason</code>: its \"Coming soon: …\" in the muted colour, never the warning colour); range, text or integer popovers, with or without options (switches with defaults, as Save layout's); confirm with a danger or primary action.",
    states: "focused entry, unavailable entry (focusable, shows its reason), planned entry, open submenu.", sizes: "Min 220 px wide.",
    when: "Actions on a target (a row, a tab, the viewport), the overflow of a crowded tab strip, a header's More.",
    combine: "Opened from an icon button with <code>menu</code>; sections built with <code>menuFromSections</code> (actionable only).",
    adapt: "Placed inside the window, flipping as needed.", drives: "Each entry's run and capability from the application.",
    a11y: "Roving focus; arrows, Home/End, type-ahead, Right opens and Left or Escape closes a submenu; focus returns to the invoker. The confirm popover is an <code>alertdialog</code> described by its sentence; focus starts on Cancel, so a stray Enter never destroys anything; Escape or a click outside cancels.",
    do: "Show only what can be done on that target. Ask before an action that can't be undone, naming the object (\"Delete “Smirk” from your library?\").", avoid: "Informational sections with nothing to do; the browser's <code>prompt</code> and <code>confirm</code>; asking before an action Undo can reverse.", see: ["c-context", "c-popover"] },
  { id: "lib-item-list", title: "Ordered list", category: "General", module: "item-list.ts", exports: ["ItemList"],
    what: "Ordered, selectable rows with pointer and keyboard reordering and inline rename.",
    anatomy: "Grip · lead slot · main button (name, meta) · trailing slot.", variants: "decorated leads and trailing actions per owner.",
    states: "selected, dragging, renaming, disabled.", sizes: "32 px rows (<code>--row-h</code>).",
    when: "Presets and layers.", combine: "Under a list head with its count and Add button.", adapt: "Names clamp; meta stays right.",
    drives: "Intents (select, move, rename, delete, duplicate, menu); the owner dispatches actions.",
    a11y: "One tab stop (roving); arrows move, Alt+arrows reorder, F2 renames, Delete removes, Shift+F10 opens the menu.",
    do: "Use it for any ordered collection.", avoid: "Selectable rows built from scratch.", see: ["c-rows"] },
  { id: "lib-tab-strip", title: "Tab strip", category: "General", module: "components/tab-strip.ts", exports: ["TabStrip", "planTabs", "TAB_STAGES"],
    what: "A row of tabs (or a column on a folded strip) that condenses instead of overflowing.",
    anatomy: "Tablist of tabs · \"more tabs\" button when some overflow. Each tab: padding at both ends (12 px on a bar, 8 px on a strip; 6 px once condensed) · icon (14 px, centred across the bar) · 6 px gap · label · 6 px gap · close mark (an 18 px target, the active tab only) · hairline to the next tab. The active tab is raised to the panel surface with the indicator along its outer edge.",
    variants: "horizontal; vertical (a group folded along a row): the same tab turned on its side, as every tab rule is written in logical properties; upright icons, labels reading top to bottom, the indicator down the strip's outer edge.",
    states: "Stages, each tried only when the one before doesn't fit: <strong>full</strong>; <strong>truncated</strong> (inactive labels cut short); <strong>icons</strong> (inactive tabs icon-only, then the active one too); <strong>overflow</strong> (tabs that still don't fit move into the menu; the active tab always stays).",
    sizes: "32 px tall (<code>--tab-h</code>); a vertical strip 36 px wide; truncated labels 7.5 em; active label up to 9 em once others are icons. Hover and selection change colour only, never size.",
    when: "Every tab group (the dock); any future tabbed surface.",
    combine: "Inside a Panel header, which gives it the room its actions leave.",
    adapt: "Refits whenever its header's size changes (one ResizeObserver per dock). Its <code>fullLength</code> (every label whole) doesn't change with the stage, so an owner can size it by that.",
    drives: "Intents (select, close, key, context menu, pointer down); the owner turns them into layout operations.",
    a11y: "<code>role=tablist/tab</code>, roving focus; a folded strip is <code>aria-orientation=vertical</code> and its owner moves along it with Up and Down as well as Left and Right; every tab is named by its label and titled by its label and context, so icon-only tabs still say what they are; the more button names the tabs it holds; the focus ring is drawn inside the tab, so a clipped strip never cuts it.",
    do: "Give every tab an icon (it is what remains). Write tab spacing in logical properties so the vertical strip follows.", avoid: "Scrolling tab strips; tabs that lose their names; physical left/right padding on tabs (it collapses on a strip).", see: ["d-group", "d-collapse"] },
  { id: "lib-panel-header", title: "Panel header", category: "General", module: "components/panel-header.ts", exports: ["PanelHeader", "HeaderFitter", "DRAG_MIN"],
    what: "A tab group's bar: tab strip, drag area, actions.",
    anatomy: "Tab strip · drag area (at least 24 px) · actions (restore, collapse or expand, layout options).",
    variants: "horizontal; vertical (a folded strip).",
    states: "expanded, collapsed (a header row or a vertical strip), maximized (with Restore), focus within.",
    sizes: "32 px tall; 36 px wide as a vertical strip.",
    when: "Every docked or floating group.", combine: "The dock builds one per group; features never build headers.",
    adapt: "The actions never shrink or scroll: however narrow the group, collapse, expand and the menu stay whole; the tab strip gives up space first. A stack of vertical strips shares its column by each header's <code>naturalLength()</code>, so a strip condensed in a short window gets its labels back when the window grows.",
    drives: "The dock's layout state.",
    a11y: "Actions are named icon buttons (\"Expand Colour & finish, Shape…\" with <code>aria-expanded</code>; \"Layout options for…\" with <code>aria-haspopup</code>).",
    do: "Keep header actions to three.", avoid: "Putting panel content controls in the header.", see: ["d-group", "d-collapse", "d-summon"] },
  { id: "lib-status", title: "Badge, note, empty state and progress", category: "General", module: "controls.ts, components/progress.ts",
    exports: ["badge", "note", "emptyState", "EmptyState", "progressBar", "section"],
    what: "The small vocabulary of state: badges qualify, notes say what the person can act on, empty states explain an empty area and offer the next step, progress bars show running work.",
    anatomy: "Badge: bevelled pill of uppercase words. Note: one muted paragraph. Empty state: dashed box, title, body, actions. Progress: 3 px bar, determinate or sweeping.",
    variants: "badge tones (neutral, accent, info, success, warning, error); note tones (muted, info, warning); empty state static or updatable (<code>EmptyState</code>, a live region); progress determinate or indeterminate.",
    states: "As their tones; a progress bar hidden when idle (the owner reserves its room).", sizes: "Badge 19 px; progress 3 px.",
    when: "Whenever a result could be mistaken for more than it is; every empty list; any wait longer than a moment.",
    combine: "A progress bar always pairs with a line saying what is happening; an empty state carries the one next step as a button.",
    adapt: "Text wraps; nothing moves when they appear where a note line or progress room is reserved.",
    drives: "Read-only snapshots.", a11y: "Progress is <code>role=progressbar</code> named by a label and valued while determinate; an updatable empty state is <code>role=status</code>.",
    do: "Use the fixed vocabulary (Working, Preview only, Can be built, Current, Stale, Blocked).", avoid: "Hand-built progress bars without a role; colour-only status.", see: ["c-chips", "c-progress", "c-empty"] },
  { id: "lib-layout", title: "Layout primitives", category: "Layout", module: "components/layout.ts", exports: ["stack", "blockSection", "PageHeader", "propertyList", "codeBlock"],
    what: "The spacing between distinct pieces of content, defined once from the spacing tokens, so no section sits against the next.",
    anatomy: "Stack: children in a column. Block section: heading row (title, help, actions), then content. Page header: back action on its own row, title with actions, meta line. Property list: key/value rows. Code block: preformatted text.",
    variants: "Stack gaps <code>tight</code> (--sp-3, parts of one thing), <code>normal</code> (--sp-4, rows of a section), <code>loose</code> (--sp-6, sections of a panel); block heading h3–h5; property values in the monospace token.",
    states: "An empty page-header meta line takes no room.",
    sizes: "Page header: back to title 8 px, title to meta 8 px, a loose gap after. Block title in the display face at <code>--fs-md</code>. Code block up to 40 vh tall, <code>--font-mono</code> at <code>--fs-2xs</code>.",
    when: "Every pane that shows more than one kind of content: a node and its facts, notes and bytes.",
    combine: `The Save Explorer is the reference: ${code("stack({ gap: \"loose\" }, header.element, splitView.element)")} with ${code("blockSection({ title: node.name }, propertyList(facts), note(text), codeBlock(hex, { label: \"Bytes\" }))")}.`,
    adapt: "Page-header actions wrap under the title when narrow; property values wrap; code blocks scroll both ways rather than wrapping or clipping.",
    drives: "Nothing: pure layout.", a11y: "Page header is a <code>header</code>; block sections are named sections; the code block is a focusable region named by its label so the keyboard can scroll it.",
    do: "Separate distinct content with a stack gap, never with ad hoc margins.", avoid: "Pixel margins between siblings; clipping preformatted text." },
  { id: "lib-tree-view", title: "Tree view", category: "General", module: "components/tree-view.ts", exports: ["TreeView", "TREE_ROW_HEIGHT", "favouriteToggle"],
    what: "Groups of rows, one nesting level, virtualised for thousands of rows (poses by pack, expressions by source).",
    anatomy: "Frame (the owner sizes it, or it fits its content with <code>maxRows</code>) · empty line at its top · the scrolling tree: group items (chevron, label, secondary text, badges, count) and row items (label with match highlights, secondary text, badges, trailing action slot) · loading status pinned to the frame's corner.",
    variants: "<code>maxRows</code> (and <code>minRows</code>): the frame fits its visible items up to that many rows, then scrolls, with no resize grip, and an empty tree fits its message; with or without trailing actions (the favourite toggle: outline star off, filled on, named \"Add to favourites\" or \"Remove from favourites\"); search highlights; secondary text.",
    states: "group open or closed; row current (<code>aria-current</code>), disabled (focusable, reason as tooltip and description, never activates), focused (kept in the tree when its item leaves: the item that took its place, else the one before); loading (pinned, never scrolls, the rows never move); empty (the message at the top); empty groups hidden.",
    sizes: "Every item 28 px (<code>TREE_ROW_HEIGHT</code>); rows indented by the chevron's width.",
    when: "Long grouped lists where one click applies the item. Short ordered lists use the Ordered list.",
    combine: `A Search field above with ${code("onArrowDown: () => tree.focus()")}; rows carry ${code("trailingState")} and the owner's ${code("onKey")} maps F to the favourite toggle.`,
    adapt: "Only the items in view plus a margin (and the focused one) are in the page, following the tree's size as well as scrolling; updates reuse items by kind and ID (a group and a row may share an ID), so focus and scroll survive. The label keeps priority: the secondary text shrinks first and hides in a tree narrower than about 320 px; the full text is the item's tooltip and accessible name.",
    drives: "<code>update({ groups, expanded, current, loading })</code> from the owner's snapshot; <code>onActivate(rowId)</code>; <code>onToggle(groupId, expanded)</code> (the owner persists the expanded set, e.g. in <code>UIPreferences.folded</code>); <code>onMenu(item, anchor)</code> for an item's context menu (a saved expression's Rename and Delete).",
    a11y: "The WAI tree pattern, flat and virtualised: <code>role=tree</code> of <code>treeitem</code>s with <code>aria-level</code>, <code>aria-setsize</code>, <code>aria-posinset</code> and, on groups, <code>aria-expanded</code>; one tab stop; Up/Down, Home/End, Right opens or enters, Left closes or goes to the group, Enter activates, Space toggles a group, type-ahead; Shift+F10 or the Menu key opens an item's context menu (as a right-click does); names include secondary text and badges; trailing actions are outside the tab order; the loading status and the empty message are outside the tree, which holds only its items.",
    do: "Give disabled rows a plain reason.", avoid: "Rendering every row; a separate select step before applying." },
  { id: "lib-folder-setting", title: "Folder setting", category: "General", module: "components/folder-setting.ts", exports: ["FolderSetting"],
    what: "One folder the app needs (the game, a Mod Organizer 2 instance, the saves folder): what it uses now and the ways to change it.",
    anatomy: "Label with help tip · \"Using: …\" or \"Detected: …\" line, or the found folders as choices (each its path and where it was found, the one in use pressed) · Choose another folder… · Use the detected folder · Don't use a folder (an optional folder) · text box with Save, Cancel and guidance (hosts without a picker) · refusal line (reserved while the text box is open).",
    variants: "with a native picker (the desktop, behind its capability) or a text box (localhost); with one detected folder, several found folders shown as choices (`found` with `onSelect`: the game through Steam and GOG), or none; optional (`onClear`).",
    states: "detected (using what the app found), chosen, chosen from the found choices (pressed), not chosen yet, typing, saving (actions unavailable, \"Saving…\"), refused (the reason inline), disabled with its reason.",
    sizes: "Full width; buttons small.",
    when: "Every folder setting: Settings › Game's game folder, Mod Organizer 2 instance and extra mod folder use it with their found folders as choices (show the options, don't hide them in a dropdown).",
    combine: `In a settings section, one per folder: ${code("new FolderSetting({ label: \"Cyberpunk 2077 folder\", onChoose, onPick, onUseDetected, onSelect, onClear })")} updated with ${code("{ chosen, detected, found, canPick, pickCapability }")}. Defaults first: while nothing is chosen, the owner saves the first found folder, so nothing needs a click.`,
    adapt: "The folder line wraps anywhere; actions wrap under it.",
    drives: "The owner's intents return an outcome; a refusal's message is shown inline, a cancelled picker says nothing. The owner passes display paths (placeholder-style), never raw paths to log.",
    a11y: "The text box is named \"&lt;label&gt;: type the folder\" and described by the refusal line; Enter saves, Escape cancels and returns focus to Choose another folder…; unavailable actions keep focus and say why.",
    do: "Detect first; offer the text box only where there is no picker.", avoid: "Refusals as toasts; showing full private paths; a Save button for the whole form; an empty reserved line under every folder." },
  { id: "lib-split-view", title: "Split view", category: "Layout", module: "components/split-view.ts", exports: ["SplitView"],
    what: "A master/detail pair inside a panel with a resizing gutter between them.",
    anatomy: "Start pane · 16 px gutter (a 1 px line, 2 px signal on hover or focus) · end pane.",
    variants: "initial share, minimum side width, session key.", states: "rest, dragging, focused gutter, stacked (narrow).",
    sizes: "Each side at least <code>min</code> (200 px by default).",
    when: "A list or tree and the inspector for its selection.", combine: "Under a page header, inside a loose stack.",
    adapt: "Below 560 px of its own width (a container query) the sides stack, master above detail, a loose gap apart.",
    drives: "Presentation state; the share is kept for the session.",
    a11y: "The gutter is a focusable <code>separator</code> named \"Resize &lt;label&gt;\" with its value; arrows adjust (Shift for bigger steps), Home and End go to the limits, Enter or a double-click shares evenly.",
    do: "Name what the gutter resizes.", avoid: "Two panes touching without a gutter." },
  { id: "lib-splitter", title: "Splitter", category: "Layout", module: "components/splitter.ts", exports: ["Splitter"],
    what: "The focusable bar between two resizable sides: a split view's gutter and the dock's splitters.",
    anatomy: "A bar across the split (its look is the owner's class: the dock's 4 px bar, the split view's 16 px gutter) with its line lit on hover, drag or focus.",
    variants: "<code>axis</code> row (side by side, a vertical bar) or column (one above the other); with or without Home and End (<code>onLimit</code>).",
    states: "rest, hover, dragging (the owner's <code>active</code> class), focused (its line lit, no outline).",
    sizes: "As its owner's class; the whole bar is the target.",
    when: "Whenever two sides share space and the person may resize them.", combine: "Inside a Split view (its gutter) or between dock cells.",
    adapt: "Its owner hides it where the sides don't resize (a stacked split view); an inert dock splitter is a plain spacer instead.",
    drives: "Intents only: <code>onStep(direction, big)</code>, <code>onEqualize()</code>, <code>onLimit(end)</code> and <code>onPointerDown(event)</code>; the owner resizes and calls <code>setValue(share)</code>.",
    a11y: "A focusable <code>separator</code> with <code>aria-orientation</code>, a name (\"Resize …\") and its first side's share as <code>aria-valuenow</code>; the arrows across the bar step (Shift for a bigger step), Enter or a double-click evens the sides, Home and End go to the limits where the owner has them.",
    do: "Name what it resizes.", avoid: "A hand-built separator with its own keys: compose this one." },
  { id: "lib-swatch-card", title: "Swatch card", category: "Feature-specific", module: "components/swatch-card.ts",
    exports: ["SwatchCard", "sampleBackground", "contrastMark", "setContrastMark", "CONTRAST_WORDS"],
    what: "A larger look at one colour swatch, beside it, while the pointer rests on it or it has keyboard focus: the colour as it really is, its name and where it comes from. With it, the contrast-enhanced marker: a small icon a row of swatches shows while its list spreads similar colours apart (cc-swatch-display.ts, swatch-contrast.ts), so the list can be read at a glance and the card and the row's own chip keep the truth.",
    anatomy: "Swatch items carry no tooltip of their own: the card names them. Card: 48 px sample (a 24 × 64 px root-to-tip chip for a gradient) in a bevelled frame on the sunken ground · name (bold) · source (muted) · when the list is enhanced, a rule and \"True colour. The list shows similar colours further apart.\" Marker: a help tip (18 px button) with a half-filled circle, muted; its tip reads \"Colours shown with more contrast so you can tell them apart; hover a swatch for its true colour.\"",
    variants: "Flat colour or gradient sample; with or without source; with or without the true-colour line. The marker on or off.",
    states: "hidden; waiting (the pointer came to rest, 120 ms); shown for one swatch (moving to the next swatch follows at once); hidden again on leave, blur, Escape, a press or scrolling. Keyboard focus keeps its card when the pointer leaves. The marker off keeps its place, invisible.",
    sizes: "Card up to 280 px wide (less on a narrow viewport), placed above the swatch, or below when there is no room, inside the viewport with a 6 px margin.",
    when: "Colour grids whose swatches are too small to judge by eye (the Character panel's colour rows). The marker only where a list shows swatches contrast-enhanced.",
    combine: `A Choice list shows it with its <code>swatchCard</code> option (and the marker beside its label with <code>update(value, capability, { enhanced })</code>); any other list of <code>choiceItem</code>s calls ${code("attachSwatchCard(list, item => sampleFor(item))")}, which uses the page's one card (<code>swatchCard()</code>). Beside a row's own true-colour chip: ${code("setContrastMark(mark, state.enhanced.size > 0)")}.`,
    adapt: "Floats: never moves the layout and takes no pointer events. The text wraps; the sample keeps its size.",
    drives: "Presentation only: the owner supplies each swatch's sample from its snapshot (the true colour from the display state's <code>truth</code>).",
    a11y: "<code>role=tooltip</code>; the swatch is described by the card while it shows (<code>aria-describedby</code>); keyboard focus shows it at once and Escape hides it. The marker is a help tip: a real button in the tab order named \"About More contrast\", its tip as its description, shown on rest, focus or a click; off, it is invisible and out of the tab order. It never sits inside another button. The row's description also says \"More contrast\". Forced colours keep the sample's real colour.",
    do: "Show the true colour, not the enhanced one; say where it comes from; keep the marker next to the row's own true-colour chip.",
    avoid: "Invented or brightened colours presented as true; a card that takes clicks or moves the layout; a marker that appears when nothing was enhanced.",
    see: ["c-creator"] },
];

const row = (label: string, value: string) => `<dt>${label}</dt><dd>${value}</dd>`;
function entry(item: LibraryEntry) {
  return `<article class="pattern wide" id="${item.id}" data-status="implemented">
  <header class="pattern-head"><h3>${esc(item.title)}</h3><span class="status-tag implemented">Implemented</span></header>
  <div class="specimen" data-compare><div class="live-specimen" data-live="${item.id}"><p class="note">Scripts build this specimen from the production component.</p></div></div>
  <dl class="guidance">${row("What", item.what)}${row("Module", `${code(`studio-ui/${item.module}`)} · ${item.exports.map(name => code(name)).join(", ")} · ${item.category}`)}${row("Anatomy", item.anatomy)}${row("Variants", item.variants)}${row("States", item.states)}${row("Sizes", item.sizes)}${row("When", item.when)}${row("Combine", item.combine)}${row("Adapt", item.adapt)}${row("Driven by", item.drives)}${row("Keyboard &amp; access", item.a11y)}${row("Do", item.do)}${row("Avoid", item.avoid)}${item.see?.length ? row("See also", item.see.map(id => `<a href="#${id}">${id}</a>`).join(", ")) : ""}</dl>
</article>`;
}

export function library() {
  const categories: LibraryCategory[] = ["General", "Layout", "Feature-specific"];
  const rule = `<article class="pattern wide" id="lib-rule" data-status="rule">
  <header class="pattern-head"><h3>Component-first UI</h3><span class="status-tag rule">Rule</span></header>
  <dl class="guidance">${row("What", "All UI is composed from this library. Panels and feature views compose components and wire them to actions and snapshots; they do not build controls (buttons, fields, lists, tabs, dialogs, progress) from raw elements. Components that only one feature needs still live in the library, in the Feature-specific category.")}${row("When", `A feature that needs a control the library lacks specifies it (behaviour, states, accessibility) and the UI component track builds or extends it here, with its entry on this page. ${code("tests/ui-component-ratchet.test.ts")} counts the ad hoc controls left outside the library per file: no file may gain one, and each count only goes down.`)}${row("Categories", categories.map(category => `${category}: ${LIBRARY.filter(item => item.category === category).map(item => `<a href="#${item.id}">${esc(item.title)}</a>`).join(", ") || "none yet (the finish chooser, creator choice grid and viewport tool strip move here next; research/authoring/ui-component-library.md)"}`).join("<br>"))}</dl>
</article>`;
  return `<section class="guide-section" id="library" aria-labelledby="library-title">
  <header class="guide-section-head"><span class="section-number">05</span><h2 id="library-title">Component library</h2></header>
  <p class="section-intro">Every component panels and features compose, with its full contract: purpose, anatomy, variants, states, sizes, how it adapts,
  keyboard and access, do and avoid, and a composition example. Import from <code>src/studio-ui/components</code>. Each specimen is built live by the production component.</p>
  <div class="patterns">${[rule, ...LIBRARY.map(entry)].join("\n")}</div>
</section>`;
}
