# Writes the git commit and tree state into a generated header on every build, so the DLL and
# the self-test record exactly which source they were built from. tools/package.ts reads the
# marker back out of the DLL and refuses to package a build from a dirty tree or another commit.
#
#   cmake -DSOURCE_DIR=<project dir> -DOUTPUT=<header> -P BuildInfo.cmake
#
# The header is rewritten only when its content changes, so an unchanged tree does not rebuild.

find_package(Git QUIET)
set(commit "unknown")
set(dirty 1)
if(GIT_FOUND)
  execute_process(
    COMMAND "${GIT_EXECUTABLE}" rev-parse HEAD
    WORKING_DIRECTORY "${SOURCE_DIR}"
    OUTPUT_VARIABLE git_commit
    RESULT_VARIABLE git_result
    OUTPUT_STRIP_TRAILING_WHITESPACE
    ERROR_QUIET)
  if(git_result EQUAL 0 AND git_commit MATCHES "^[0-9a-f]+$")
    set(commit "${git_commit}")
    # Only this project's files count; build/ and dist/ are ignored.
    execute_process(
      COMMAND "${GIT_EXECUTABLE}" status --porcelain -- .
      WORKING_DIRECTORY "${SOURCE_DIR}"
      OUTPUT_VARIABLE git_status
      RESULT_VARIABLE status_result
      OUTPUT_STRIP_TRAILING_WHITESPACE
      ERROR_QUIET)
    if(status_result EQUAL 0 AND git_status STREQUAL "")
      set(dirty 0)
    endif()
  endif()
endif()

set(content "#pragma once\n// Generated by native/cmake/BuildInfo.cmake on every build. Do not edit.\n#define XFB_BUILD_COMMIT \"${commit}\"\n#define XFB_BUILD_DIRTY ${dirty}\n")
if(EXISTS "${OUTPUT}")
  file(READ "${OUTPUT}" existing)
else()
  set(existing "")
endif()
if(NOT existing STREQUAL content)
  file(WRITE "${OUTPUT}" "${content}")
endif()
