/**
 * Values of properties a file leaves out. Pure. A CR2W file omits a property whose value equals the class default, and the
 * resolver's JSON has every property, so the reader writes the default. Two sources, in order:
 *
 * 1. `rtti-defaults.json`: per class and property, the value the reference JSON shows when the file omits the property,
 *    generated by tools/native-cr2w-diff.ts from WolvenKit 9.0.1 output of game 2.31 and installed mods [resource: tool output
 *    compared with the binary; knowledge/archive-format.md §6.3]. Looked up along the class's base classes.
 * 2. Otherwise the type's zero value: 0, `0` for Bool, "0" for 64-bit integers, `None` names, empty arrays and `{Elements: []}`,
 *    null handles and buffers, empty references (flag `Soft` for `raRef`), the zero member of an enum, "0" for a bitfield, and a
 *    struct of its own defaults.
 */
import learned from "./rtti-defaults.json";
import { RedObject } from "./red-model";
import { emptyReference } from "./red-values";
import { baseClasses, enumMembers, kindOf } from "./rtti";

const table = learned as unknown as Record<string, Record<string, unknown>>;

/** The learned default of `type.property` (or of a base class's), or undefined. */
export function learnedDefault(type: string, property: string): unknown {
  for (const name of baseClasses(type)) {
    const row = table[name];
    if (row && Object.hasOwn(row, property)) return row[property];
  }
  return undefined;
}

/** Learned keys by type. Type names come from files, so the memo is bounded (cleared when full). */
const keysMemo = new Map<string, string[]>();
const MAX_KEYS_MEMO = 4096;
/**
 * Properties the reference JSON writes for `type` beyond its RTTI ones (derived or newer properties, learned with their defaults),
 * along its base classes.
 */
export function learnedKeys(type: string): string[] {
  let keys = keysMemo.get(type);
  if (!keys) {
    keys = [...new Set(baseClasses(type).flatMap(name => Object.keys(table[name] ?? {})))];
    if (keysMemo.size >= MAX_KEYS_MEMO) keysMemo.clear();
    keysMemo.set(type, keys);
  }
  return keys;
}

/** Test hook: how many types the learned-keys memo holds. */
export const learnedKeysMemoSize = () => keysMemo.size;

/** The zero value of a type string. */
export function defaultValue(type: string): unknown {
  if (/^array:/.test(type)) return [];
  if (/^static:\d+,/.test(type) || /^\[\d+\]/.test(type)) return { Elements: [] };
  if (/^w?handle:/.test(type)) return null;
  if (/^rRef:/.test(type)) return emptyReference(false);
  if (/^raRef:/.test(type)) return emptyReference(true);
  switch (type) {
    case "Bool": case "Int8": case "Uint8": case "Int16": case "Uint16": case "Int32": case "Uint32": case "Float": case "Double": return 0;
    case "Int64": case "Uint64": case "CRUID": return "0";
    case "CName": return { $type: "CName", $storage: "string", $value: "None" };
    case "String": return "";
    case "NodeRef": return { $type: "NodeRef", $storage: "string", $value: "" };
    case "TweakDBID": return { $type: "TweakDBID", $storage: "uint64", $value: "0" };
    case "CDateTime": return "1048576";
    case "CGUID": return "AAAAAAAAAAAAAAAAAAAAAA==";
    case "LocalizationString": case "DataBuffer": case "serializationDeferredDataBuffer": case "SharedDataBuffer": case "CVariant": return null;
    case "gamedataLocKeyWrapper": return {};
  }
  const kind = kindOf(type);
  if (kind === "enum") return enumMembers(type)?.find(([, value]) => value === 0)?.[0] ?? "0";
  if (kind === "bitfield") return "0";
  if (kind === "class") return new RedObject(type);
  return null;
}
