/**
 * The slice of the game's RTTI the native reader uses (`rtti-subset.json`, generated by tools/native-rtti-subset.ts from an RTTI
 * dump). Pure. It answers whether a type name is an enum, a bitfield or a class, gives a class's properties with inherited ones
 * first, and gives enum and bitfield members. Classes outside the subset are still read (a CR2W file names every property's
 * type); only their unwritten defaults are unknown.
 */
import subset from "./rtti-subset.json";

type ClassRow = [parent: string, props: [name: string, type: string][]];
const classes = subset.classes as unknown as Record<string, ClassRow>;
const enums = subset.enums as unknown as Record<string, [string, number][] | 0>;
const bitfields = subset.bitfields as unknown as Record<string, [string, number][]>;

export type TypeKind = "enum" | "bitfield" | "class" | "other";

/** What a bare type name (no `array:`/`handle:` prefix) is, as far as the RTTI slice knows. */
export function kindOf(type: string): TypeKind {
  if (Object.hasOwn(enums, type)) return "enum";
  if (Object.hasOwn(bitfields, type)) return "bitfield";
  if (Object.hasOwn(classes, type)) return "class";
  return "other";
}

export const isKnownClass = (type: string) => Object.hasOwn(classes, type);

const propsMemo = new Map<string, readonly (readonly [string, string])[]>();
/** A class's properties, base classes' first, or null when the class is outside the slice. */
export function classProperties(type: string): readonly (readonly [string, string])[] | null {
  if (!Object.hasOwn(classes, type)) return null;
  let props = propsMemo.get(type);
  if (!props) {
    const chain: ClassRow[] = [];
    for (let name = type; name && Object.hasOwn(classes, name); name = classes[name]![0]) chain.unshift(classes[name]!);
    props = chain.flatMap(row => row[1].map(([name, t]) => [name, t] as const));
    propsMemo.set(type, props);
  }
  return props;
}

const propertyTypesMemo = new Map<string, ReadonlyMap<string, string>>();
/**
 * The RTTI type of `type.property`, or null when the slice does not know the class or the property. Memoised for classes in the
 * slice only, so the cache is bounded by the slice, not by the files read.
 */
export function propertyType(type: string, property: string): string | null {
  let types = propertyTypesMemo.get(type);
  if (!types) {
    const props = classProperties(type);
    if (!props) return null;
    types = new Map(props.map(([name, t]) => [name, t]));
    propertyTypesMemo.set(type, types);
  }
  return types.get(property) ?? null;
}

/** `static:N,T` and `[N]T` name the same type; everything else compares as text. */
const canonicalType = (type: string) => type.replace(/static:(\d+),/g, "[$1]");
/** Whether a stored type string names the RTTI's type. */
export const sameType = (stored: string, rtti: string) => stored === rtti || canonicalType(stored) === canonicalType(rtti);

/** `type` and its base classes, nearest first (as far as the slice knows them). */
export function baseClasses(type: string): string[] {
  const out: string[] = [];
  for (let name = type; name && !out.includes(name); name = Object.hasOwn(classes, name) ? classes[name]![0] : "") out.push(name);
  return out;
}

/** Members of an enum as [name, value], or null when the slice keeps only its name. */
export function enumMembers(type: string): readonly [string, number][] | null {
  const members = enums[type];
  return Array.isArray(members) ? members : null;
}

/** Members of a bitfield as [name, bit]. */
export const bitfieldMembers = (type: string): readonly [string, number][] => bitfields[type] ?? [];
