/**
 * The direct-read ratchet (profiles and graph design §5.1, boundary rule 3): every source of non-determinism enters as
 * a source node, so only adapter modules read the wall clock, timers, randomness, the file system, the network,
 * browser storage or the game bridge directly. Today's code reads them in many places; each is listed below with what
 * it reads, and the list may only shrink: a new read fails, and a listed read that is gone fails until its row is
 * removed (each slice empties the rows it touches, §5.3). New graph code is held to the rule from its first line.
 * Regenerate the rows with `bun tests/fixtures/direct-reads.ts` only when removing them.
 */
import { expect, test } from "bun:test";
import { directReads, kindsIn } from "./fixtures/direct-reads";

/**
 * Grandfathered direct reads (module: kinds), recorded when the graph engine landed (G1) and extended once at its merge for modules
 * written in parallel before the rule existed (the speed and beta-polish tracks). This list only shrinks.
 */
const GRANDFATHERED: Readonly<Record<string, readonly string[]>> = {
  "archive-inventory-fs": ["files"],
  "authoring-eye-makeup": ["random"],
  "brow-study-fixture": ["network"],
  "browser-cc-catalogue-device": ["timers","network"],
  "browser-character-detail-device": ["timers","random","network"],
  "browser-choice-preview-device": ["network"],
  "browser-desktop-app-device": ["network"],
  "browser-facial-device": ["network"],
  "browser-file-device": ["timers"],
  "browser-grading-lut-device": ["timers","network"],
  "browser-head-attachment": ["timers"],
  "browser-install-detection-device": ["network"],
  "browser-local-setup-device": ["network"],
  "browser-mod-install-device": ["network"],
  "browser-pose-device": ["network"],
  "browser-save-explorer-device": ["network"],
  "cc-catalogue-host": ["files"],
  "cc-catalogue-service": ["clock","timers"],
  "cc-icon-host": ["clock","files"],
  "cc-swatch-host": ["clock","timers","files"],
  "character-context-actions": ["clock","timers"],
  "character-detail-host": ["clock","timers","files"],
  "character-detail-loader": ["timers"],
  "character-detail-service": ["clock","files"],
  "choice-manifest": ["files"],
  "choice-prefetch": ["clock","timers"],
  "choice-preview-host": ["files"],
  "choice-preview-render": ["clock"],
  "choice-preview-service": ["clock","timers"],
  "choice-preview-worker": ["clock","network"],
  "clothing-host": ["clock","files"],
  "collection-service": ["clock","random"],
  "collection-session": ["random"],
  "collection-store": ["clock","random"],
  "collection-transport": ["network"],
  "dangle-host": ["files"],
  "derived-cache": ["files"],
  "desktop-app-host": ["timers","files"],
  "diagnostics/actions": ["timers"],
  "diagnostics/browser-device": ["clock","timers"],
  "diagnostics/host-endpoint": ["files"],
  "diagnostics/host-log": ["clock","files"],
  "diagnostics/host-report": ["clock","files"],
  "diagnostics/mod-identity": ["files"],
  "diagnostics/model": ["clock","random"],
  "diagnostics/trace-window": ["timers","files"],
  "diagnostics/zip": ["clock"],
  "dotnet-runtime": ["clock","files"],
  "engines/layered-makeup/raster-processor": ["clock","timers"],
  "event-loop": ["clock"],
  "expressions-game-prerequisite": ["network","files"],
  "eye-plate-cache": ["clock"],
  "eye-plate-prerequisite": ["files"],
  "eye-plate-service": ["files"],
  "eye-plate-wolvenkit": ["files"],
  "facial-host": ["clock","timers","files"],
  "facial-prefetch": ["timers"],
  "facial-preview": ["clock","timers"],
  "features/expressions/export/index": ["files"],
  "features/expressions/verify/index": ["files"],
  "features/eye-makeup/export/plate-input": ["files"],
  "features/eye-makeup/render/index": ["timers"],
  "features/eye-makeup/verify/verify-build": ["files"],
  "features/eye-makeup/view/uv": ["timers"],
  "features/poses/actions": ["timers"],
  "features/poses/host/preferences-store": ["files"],
  "features/save-explorer/actions": ["clock","timers"],
  "features/save-explorer/host/saves-server": ["files"],
  "features/save-explorer/view/panel": ["timers"],
  "game-asset-export": ["clock","files"],
  "game-asset-export-wolvenkit": ["files"],
  "game-blink": ["timers"],
  "grading-lut-host": ["clock","files"],
  "host-state-poller": ["timers"],
  "idle-host": ["clock","timers","files"],
  "install-detection-host": ["files"],
  "installation-registry": ["clock","timers","files"],
  "library-store": ["clock","random"],
  "lighting-setup-stage": ["clock","timers"],
  "local-settings-readiness": ["files"],
  "local-settings-server": ["files"],
  "local-settings-store": ["files"],
  "mod-install-host": ["files"],
  "mod-install-transport": ["clock","files"],
  "native-geometry-export": ["clock","files"],
  "native-texture-export": ["clock","files"],
  "native/archive-reader": ["files"],
  "native/native-decode": ["clock","timers"],
  "native/native-fetch-port": ["network"],
  "native/oodle": ["files"],
  "package-action": ["network"],
  "package-bake": ["files"],
  "package-resource-builder": ["files"],
  "package-server": ["files"],
  "part-preset-store": ["clock","random"],
  "part-presets": ["timers","network"],
  "plate-uv-footprint-io": ["files"],
  "platform/core/look-history": ["clock"],
  "platform/export/check-runner": ["timers"],
  "platform/export/product-builder": ["clock","files"],
  "platform/export/product-host": ["clock","timers","files"],
  "platform/export/product-verifier": ["files"],
  "platform/scene/character-renderer": ["clock","timers"],
  "platform/scene/face-driver": ["timers"],
  "platform/scene/idle-source": ["clock","timers","network"],
  "platform/scene/orbit-limits": ["timers"],
  "platform/scene/scene-host": ["clock","timers"],
  "pose-catalogue-host": ["clock","files"],
  "prepared-files": ["files"],
  "preview-core-host": ["files"],
  "preview-core-service": ["clock","files"],
  "preview-preparation": ["timers","network"],
  "process-tree": ["timers"],
  "raster-task-yield": ["timers"],
  "raster-worker": ["timers"],
  "rdar-index-fs": ["files"],
  "render-fidelity-study": ["network"],
  "resolver-host": ["clock","timers","network","files"],
  "resource-graph": ["network"],
  "route-fingerprint": ["files"],
  "runtime-diagnostic-promotion": ["files"],
  "runtime-diagnostic-stage": ["files"],
  "saves-host-sources": ["files"],
  "showroom/build": ["files"],
  "showroom/verify": ["files"],
  "source-discovery": ["clock","files"],
  "studio-application": ["random"],
  "studio-file-operations": ["clock"],
  "studio-main": ["storage"],
  "studio-startup": ["clock","timers"],
  "studio-ui/app": ["clock","timers"],
  "studio-ui/components/choice-preview": ["clock","timers"],
  "studio-ui/components/direction-dial": ["timers"],
  "studio-ui/components/listbox-keys": ["clock"],
  "studio-ui/components/search-field": ["timers"],
  "studio-ui/components/swatch-card": ["timers"],
  "studio-ui/components/tree-view": ["timers"],
  "studio-ui/controls": ["timers"],
  "studio-ui/dock/dock-view": ["timers"],
  "studio-ui/feedback": ["clock","timers"],
  "studio-ui/guidance/controller": ["clock","timers"],
  "studio-ui/guidance/desktop-app-sheet": ["clock"],
  "studio-ui/guidance/overlay": ["timers"],
  "studio-ui/input-hints": ["timers"],
  "studio-ui/item-list": ["timers"],
  "studio-ui/menu": ["timers"],
  "studio-ui/panels/character": ["timers"],
  "studio-ui/panels/game-setup": ["timers"],
  "studio-ui/panels/history": ["timers"],
  "studio-ui/panels/settings": ["timers"],
  "studio-ui/panels/viewports": ["timers"],
  "studio-ui/preview-setup-card": ["timers"],
  "studio-ui/reason-tip": ["timers"],
  "studio-ui/scroll-anchor": ["clock","timers"],
  "studio-ui/style-guide/demo": ["timers"],
  "studio-ui/style-guide/library-demo": ["timers"],
  "surface-editor": ["timers"],
  "tool-download": ["timers","files"],
  "uv-editor": ["timers"],
  "verifier-wolvenkit": ["files"],
  "vortex-host": ["files"],
  "wolvenkit-cli": ["clock","files"],
  "wolvenkit-setup": ["network"],
  "wolvenkit-setup-host": ["timers","files"],
  "workspace-persistence": ["timers"],
  "zip-extract": ["files"],
};

test("no module reads the clock, timers, randomness, files, the network, storage or the bridge directly beyond the recorded list", () => {
  expect(directReads()).toEqual(GRANDFATHERED as Record<string, string[]>);
});

test("the graph's own code (its types, the composition) reads nothing directly; its adapters are the only exception", () => {
  expect(Object.keys(directReads()).filter(name => name.startsWith("platform/graph-") || name === "compose/graph")).toEqual([]);
});

test("the ratchet's patterns see each kind of read, and not prose", () => {
  const probes: Record<string, string> = { clock: "const t = Date.now();", timers: "setTimeout(run, 5);", random: "const id = crypto.randomUUID();",
    network: "await fetch(url);", storage: "localStorage.getItem(key);", files: `import { readFileSync } from "node:fs";`, bridge: "new RuntimeBridgeClient();" };
  for (const [kind, text] of Object.entries(probes)) expect(kindsIn(text)).toEqual([kind]);
  expect(kindsIn(["// Date.now() and fetch(x) in a comment", "const a = new Date(when); clock.after(5, run);"].join(String.fromCharCode(10)))).toEqual([]);
});
