import { expect, test } from "bun:test";
import * as THREE from "three";
import { createMakeupStack } from "../src/makeup-stack";
import { initialRecipe } from "../src/recipe";

test("completed optics are size keyed, pending changes retain the complete look, and replacement disposes owned maps", () => {
  const geometry=new THREE.BufferGeometry();
  geometry.setAttribute("position",new THREE.Float32BufferAttribute([0,0,0],3));
  geometry.setAttribute("skinIndex",new THREE.Uint16BufferAttribute([0,0,0,0],4));
  geometry.setAttribute("skinWeight",new THREE.Float32BufferAttribute([1,0,0,0],4));
  const anchor=new THREE.SkinnedMesh(geometry), root=new THREE.Group();root.add(anchor);
  anchor.skeleton=new THREE.Skeleton([new THREE.Bone()]);
  const stack=createMakeupStack(anchor,4), layer=initialRecipe().layers[0];
  const canvas=(size:number)=>({width:size,height:size}) as HTMLCanvasElement;
  const optics=(size:number)=>({size,normal:new Uint8Array(size*size*4),surface:new Uint8Array(size*size*4)});
  layer.finish="glitter";
  stack.setCanvases([canvas(32),canvas(32)]);
  expect(stack.needsOptics(0,layer,32)).toBe(true);
  stack.updateLayer(0,layer);
  expect(stack.plates[0].visible).toBe(false);expect(stack.materials[0].normalMap).toBeNull();
  stack.updateLayer(0,layer,optics(32));
  expect(stack.plates[0].visible).toBe(true);expect(stack.needsOptics(0,layer,32)).toBe(false);
  expect(stack.needsOptics(0,layer,64)).toBe(true);
  const firstNormal=stack.materials[0].normalMap, oldColour=stack.materials[0].color.getHexString();
  const changed={...layer,color:"#123456",flakes:{cells:64,density:.3,tilt:.2,seed:8}};
  stack.updateLayer(0,changed);
  expect(stack.materials[0].normalMap).toBe(firstNormal);
  expect(stack.materials[0].color.getHexString()).toBe(oldColour);
  expect(stack.plates[0].visible).toBe(true);
  expect(()=>stack.updateLayer(0,changed,optics(64))).toThrow();
  expect(stack.materials[0].normalMap).toBe(firstNormal);
  let disposed=0;
  stack.materials[0].normalMap!.addEventListener("dispose",()=>disposed++);
  stack.materials[0].roughnessMap!.addEventListener("dispose",()=>disposed++);
  stack.textures[0].addEventListener("dispose",()=>disposed++);
  stack.updateLayer(1,{...layer,finish:"matte"});
  const otherTexture=stack.textures[1];
  stack.setLayerCanvas(0,canvas(64));stack.updateLayer(0,changed,optics(64));
  expect(disposed).toBe(3);
  expect(stack.plates[1].visible).toBe(true);expect(stack.textures[1]).toBe(otherTexture);
  expect(stack.materials[0].color.getHexString()).toBe("123456");
  expect(stack.diagnostics()[0]).toMatchObject({visible:true,mask:{width:64,height:64},normal:{width:64,height:64},surface:{width:64,height:64},mapCount:3,baseBytes:64*64*4*3});
  let disabledDisposals=0;
  stack.materials[0].normalMap!.addEventListener("dispose",()=>disabledDisposals++);
  stack.materials[0].roughnessMap!.addEventListener("dispose",()=>disabledDisposals++);
  stack.updateLayer(0,{...changed,enabled:false});
  expect(disabledDisposals).toBe(2);expect(stack.plates[0].visible).toBe(false);
  expect(stack.materials[0].normalMap).toBeNull();expect(stack.materials[0].roughnessMap).toBeNull();
  expect(stack.needsOptics(0,{...changed,enabled:false},64)).toBe(false);
  stack.updateLayer(0,changed);expect(stack.plates[0].visible).toBe(false);
  stack.updateLayer(0,changed,optics(64));
  let replaced=0;stack.materials[0].normalMap!.addEventListener("dispose",()=>replaced++);
  const previousMaterial=stack.materials[0];
  stack.setCanvases([canvas(1),canvas(1)]);
  expect(replaced).toBe(1);expect(stack.materials[0]).not.toBe(previousMaterial);
  expect(stack.needsOptics(0,changed,64)).toBe(true);
  expect(stack.diagnostics().every(d=>!d.visible&&d.mapCount===1&&d.mask?.width===1)).toBe(true);
  stack.setCanvases([]);
});
