import { expect, test } from "bun:test";
import { applyMo2Placement, planMo2Placement } from "../src/mo2-placement";
import { parseMo2Modlist } from "../src/mo2-instance";
import { eyeMakeupRelatedEntries } from "../src/mod-branding";

// File order is highest priority first; MO2's left pane shows it reversed, so the pane reads
// (top to bottom): CORE, LIBS, FRAMEWORKS / ArchiveXL, TweakXL / LOOKS / Legacy, Hair / OVERWRITES / Patch.
const sectioned = [
  "# This file was automatically generated by Mod Organizer.",
  "+Patch", "-OVERWRITES_separator",
  "+Hair", "+XF Eye Artistry CCXL - Dev", "-LOOKS_separator",
  "+TweakXL", "+ArchiveXL", "-CORE, LIBS, FRAMEWORKS_separator",
].join("\r\n") + "\r\n";
const place = (text: string, frameworkMods: string[] = []) =>
  planMo2Placement(text, "XF Eye Artistry", { related: eyeMakeupRelatedEntries, frameworkMods });
const paneOrder = (text: string) => parseMo2Modlist(text).entries.map(entry => entry.name).reverse();

test("a related entry puts the mod directly below it in the pane, in the same section", () => {
  const placement = place(sectioned);
  expect(placement).toMatchObject({ rule: "beside-related", anchor: "XF Eye Artistry CCXL - Dev", section: "LOOKS", row: 4 });
  expect(placement.description).toBe('Directly below "XF Eye Artistry CCXL - Dev" in the "LOOKS" section.');
  const next = applyMo2Placement(sectioned, placement);
  expect(paneOrder(next)).toEqual(["CORE, LIBS, FRAMEWORKS_separator", "ArchiveXL", "TweakXL", "LOOKS_separator",
    "XF Eye Artistry CCXL - Dev", "XF Eye Artistry", "Hair", "OVERWRITES_separator", "Patch"]);
  // Only one row is added; the rest of the file is byte-identical.
  expect(next.replace("+XF Eye Artistry\r\n", "")).toBe(sectioned);
});

test("without a related entry the mod goes where MO2 puts new mods, skipping framework sections", () => {
  const plain = sectioned.replace("+XF Eye Artistry CCXL - Dev\r\n", "");
  const bottom = place(plain);
  expect(bottom).toMatchObject({ rule: "section", section: "OVERWRITES", row: 1 });
  expect(paneOrder(applyMo2Placement(plain, bottom)).slice(-2)).toEqual(["Patch", "XF Eye Artistry"]);
  // A bottom section that holds a framework mod (by content, whatever its name) is skipped.
  const next = place(plain, ["Patch"]);
  expect(next).toMatchObject({ rule: "section", section: "LOOKS", row: 3 });
  expect(paneOrder(applyMo2Placement(plain, next))).toEqual(["CORE, LIBS, FRAMEWORKS_separator", "ArchiveXL", "TweakXL",
    "LOOKS_separator", "Hair", "XF Eye Artistry", "OVERWRITES_separator", "Patch"]);
  // A predecessor inside a framework section is not a place to sit beside.
  const inCore = "+XF Eye Artistry CCXL - Dev\r\n+ArchiveXL\r\n-Core Mods_separator\r\n+Hair\r\n-LOOKS_separator\r\n";
  expect(place(inCore)).toMatchObject({ rule: "section", section: "LOOKS", row: 3 });
});

test("an existing entry keeps its place, and edge cases stay deterministic", () => {
  const listed = sectioned.replace("+Hair", "-XF Eye Artistry\r\n+Hair");
  const existing = place(listed);
  expect(existing).toMatchObject({ rule: "existing", section: "LOOKS", row: 3 });
  expect(applyMo2Placement(listed, existing)).toBe(listed.replace("-XF Eye Artistry", "+XF Eye Artistry"));
  expect(place("# header\n+A\n+B\n")).toMatchObject({ rule: "list-end", row: 1, section: null });
  expect(applyMo2Placement("﻿+A\n", place("﻿+A\n"))).toBe("﻿+XF Eye Artistry\n+A\n");
  const allCore = "+ArchiveXL\n-FRAMEWORKS_separator\n+Loose\n";
  expect(place(allCore)).toMatchObject({ rule: "fallback", row: 0, section: "FRAMEWORKS" });
  expect(() => planMo2Placement("+A\n", "bad/name")).toThrow("Invalid mod name");
  expect(() => applyMo2Placement("+A\n", { ...existing, row: 0 })).toThrow("no longer matches");
});
