// "Add to my mod manager" (UI-82) over a fake MO2 tree and game folder: the plan names exactly what changes and where, the one
// mod-list row lands in the right separator section (the file is the reverse of MO2's pane), consent is to that plan only, and
// every refusal (a folder or files XF Studio didn't make, MO2 or the game open, a changed list, a duplicate elsewhere) changes
// nothing. The install review's fixes are pinned here too (INSTALL-01..11, UI-99..100).
import { expect, test } from "bun:test";
import { createHash } from "node:crypto";
import { chmodSync, existsSync, linkSync, mkdirSync, mkdtempSync, readdirSync, readFileSync, rmSync, statSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { defaultLocalSettings, type LocalSettings } from "../src/local-settings";
import { createModInstallHandler, installIssue, ModInstallError, ModInstallHost, READ_ONLY_VERIFICATION, windowsRunningApps,
  type RunningApps } from "../src/mod-install-host";
import { EYE_MAKEUP_MOD } from "../src/mod-branding";

const digest = (body: string | Buffer) => createHash("sha256").update(body).digest("hex");
const MOD = EYE_MAKEUP_MOD.modName;
/** A profile of three sections, frameworks at the top of the pane (the last rows of the file: MO2's pane is the file reversed). */
const MODLIST = [
  "# This file was automatically generated by Mod Organizer.",
  "+Neon Lashes",
  "-Old Hair",
  "+Looks_separator",
  "+Better Lighting",
  "+Visuals_separator",
  "+ArchiveXL",
  "+TweakXL",
  "+CORE, LIBS, FRAMEWORKS_separator",
].join("\r\n") + "\r\n";

function fixture(route: "direct" | "mo2", modlist: string | Buffer = MODLIST, options: { receipts?: string; legacy?: string[]; readOnly?: string; ansi?: number | null } = {}) {
  const root = mkdtempSync(join(tmpdir(), "xfs-mod-install-"));
  const game = join(root, "game"), mo2 = join(root, "mo2"), store = join(root, "candidates");
  const receipts = join(root, options.receipts ?? "receipts");
  const profile = "Main (2026)";
  mkdirSync(join(game, "bin", "x64"), { recursive: true });
  mkdirSync(join(game, "archive", "pc"), { recursive: true });
  writeFileSync(join(game, "bin", "x64", "Cyberpunk2077.exe"), "fixture");
  mkdirSync(join(mo2, "mods", "Neon Lashes"), { recursive: true });
  mkdirSync(join(mo2, "profiles", profile), { recursive: true });
  const modlistFile = join(mo2, "profiles", profile, "modlist.txt");
  writeFileSync(modlistFile, modlist);
  mkdirSync(store);
  const settings: LocalSettings = { ...defaultLocalSettings(), revision: 3, gameRoot: game, mo2Root: mo2, mo2ProfileId: profile, launchRoute: route };
  const running: RunningApps = { mo2: false, game: false };
  let frameworks = ["ArchiveXL", "TweakXL"];
  const revealed: string[] = [];
  const make = (receiptsRoot = receipts, legacy = options.legacy?.map(name => join(root, name))) => new ModInstallHost({ candidateStore: store,
    receiptsRoot, legacyReceiptsRoots: legacy, settings: () => settings, running: () => ({ ...running }), frameworkMods: () => frameworks,
    ansiCodePage: () => options.ansi ?? null, readOnly: options.readOnly, reveal: path => { revealed.push(path); return true; } });
  const host = make();
  const target = route === "direct" ? join(game, "archive", "pc", "mod") : join(mo2, "mods", MOD, "archive", "pc", "mod");
  function candidate(id: string, version: string, xl = `${version}-1`, modName?: string) {
    const folder = join(store, id), payload = join(folder, "archive", "pc", "mod");
    mkdirSync(payload, { recursive: true });
    const files = ["xfs_test.archive", "xfs_test.archive.xl"].map((name, index) => {
      const body = index ? xl : `${version}-0`;
      writeFileSync(join(payload, name), body);
      return { path: `archive/pc/mod/${name}`, sha256: digest(body), bytes: Buffer.byteLength(body) };
    });
    writeFileSync(join(folder, "manifest.json"), JSON.stringify(modName
      ? { schema: "xfs/local-package-2", productId: "11111111-2222-4333-8444-555555555555", modName, nameSource: "plan", archive: "xfs_test",
        features: [{ feature: "eye-makeup", namespace: "xfs_test" }], files, verifiedUnpackedFiles: 2, installed: false, gameRenderingVerified: false }
      : { schema: "xfs/local-package-1", namespace: "xfs_test", verifiedUnpackedFiles: 2, installed: false, gameRenderingVerified: false, files }));
  }
  const lines = () => readFileSync(modlistFile, "utf8").split("\r\n");
  return { root, game, mo2, store, receipts, settings, host, make, target, candidate, modlistFile, lines, revealed, running,
    setRunning: (on: boolean) => { running.mo2 = on; }, setFrameworks: (names: string[]) => { frameworks = names; },
    cleanup: () => rmSync(root, { recursive: true, force: true }) };
}
const refusal = async (run: () => Promise<unknown>) => { try { await run(); } catch (error) { return error as ModInstallError; } throw Error("Expected a refusal."); };
/** Every file under `folder`, relative, sorted (to prove nothing was written). */
const tree = (folder: string): string[] => existsSync(folder)
  ? readdirSync(folder, { recursive: true, withFileTypes: true }).filter(entry => entry.isFile()).map(entry => join(entry.parentPath, entry.name).slice(folder.length + 1)).sort()
  : [];

test("MO2: the plan names the mod, its folder and the one mod-list row, then install adds exactly that", async () => {
  const f = fixture("mo2");
  try {
    f.candidate("first", "one");
    const plan = await f.host.plan("first");
    expect(plan).toMatchObject({ route: "mo2", modName: MOD, place: "Mod Organizer 2 (profile “Main (2026)”)", blocked: null, next: null, replacing: false });
    expect(plan.changes[0]).toBe(`Add the mod “${MOD}” to Mod Organizer 2, with its 2 files in ${f.target}.`);
    // The pane shows the file reversed: the new row goes at the bottom of the first section that holds no frameworks ("Looks").
    expect(plan.changes[1]).toBe(`Add “${MOD}” to the profile “Main (2026)”, switched on. At the bottom of the "Looks" section, where Mod Organizer puts newly installed mods.`);
    expect(plan.changes[2]).toBe("Nothing else in your mod list changes.");
    const before = f.lines();
    const result = await f.host.install("first", plan.token);
    expect(result.message).toContain("switched on in the profile “Main (2026)”");
    expect(readdirSync(f.target).sort()).toEqual(["xfs_test.archive", "xfs_test.archive.xl"]);
    // One row added, directly after the comment (the bottom of the "Looks" section in the pane); nothing else moved.
    expect(f.lines()).toEqual([before[0], `+${MOD}`, ...before.slice(1)]);
    expect(readdirSync(join(f.receipts, "modlists"))).toHaveLength(1);
    expect(readdirSync(join(f.mo2, "profiles", "Main (2026)")).sort()).toEqual(["modlist.txt"]);
  } finally { f.cleanup(); }
});

test("MO2: a profile whose every section holds frameworks gets MO2's own default place, and a related entry is followed", async () => {
  const f = fixture("mo2", "+ArchiveXL\n+Frameworks_separator\n");
  try {
    f.candidate("first", "one");
    const plan = await f.host.plan("first");
    expect(plan.changes[1]).toContain("Every section in this profile holds frameworks");
    await f.host.install("first", plan.token);
    expect(readFileSync(f.modlistFile, "utf8")).toBe(`+${MOD}\n+ArchiveXL\n+Frameworks_separator\n`);
  } finally { f.cleanup(); }
  const g = fixture("mo2", `+Better Lighting\n+${EYE_MAKEUP_MOD.predecessorMods[0]}\n+Looks_separator\n`);
  try {
    g.candidate("first", "one");
    const plan = await g.host.plan("first");
    expect(plan.changes[1]).toContain(`Directly below "${EYE_MAKEUP_MOD.predecessorMods[0]}"`);
    // The older mod is named for the person to decide; it is never switched off for them.
    expect(plan.notes[0]).toContain(`“${EYE_MAKEUP_MOD.predecessorMods[0]}” is also switched on`);
    await g.host.install("first", plan.token);
    expect(readFileSync(g.modlistFile, "utf8")).toBe(`+Better Lighting\n+${MOD}\n+${EYE_MAKEUP_MOD.predecessorMods[0]}\n+Looks_separator\n`);
  } finally { g.cleanup(); }
});

test("MO2: a listed but switched-off entry is switched on where it is", async () => {
  const f = fixture("mo2", `+Neon Lashes\n-${MOD}\n+Looks_separator\n`);
  try {
    f.candidate("first", "one");
    const plan = await f.host.plan("first");
    expect(plan.changes[1]).toBe(`“${MOD}” is already in the profile “Main (2026)”; switch it on where it is.`);
    await f.host.install("first", plan.token);
    expect(readFileSync(f.modlistFile, "utf8")).toBe(`+Neon Lashes\n+${MOD}\n+Looks_separator\n`);
  } finally { f.cleanup(); }
});

test("MO2: a folder of that name XF Studio didn't create is refused, and nothing changes", async () => {
  const f = fixture("mo2");
  try {
    f.candidate("first", "one");
    mkdirSync(join(f.mo2, "mods", MOD), { recursive: true });
    writeFileSync(join(f.mo2, "mods", MOD, "readme.txt"), "someone else's mod");
    const plan = await f.host.plan("first");
    expect(plan).toMatchObject({ next: "rename" });
    expect(plan.blocked).toContain("that XF Studio didn't put there");
    expect(await refusal(() => f.host.install("first", plan.token))).toMatchObject({ code: "install_blocked" });
    expect(readFileSync(f.modlistFile, "utf8")).toBe(MODLIST);
    expect(readdirSync(join(f.mo2, "mods", MOD))).toEqual(["readme.txt"]);
  } finally { f.cleanup(); }
});

test("MO2: while Mod Organizer 2 is open the install waits, with the one next step; unknown counts as open (INSTALL-10)", async () => {
  const f = fixture("mo2");
  try {
    f.candidate("first", "one");
    f.setRunning(true);
    const plan = await f.host.plan("first");
    expect(plan.blocked).toBe("Mod Organizer 2 is open. Close it first, then try again: it rewrites its mod list when it closes, and would undo this.");
    expect(plan.next).toBe("retry");
    expect((await refusal(() => f.host.install("first", plan.token))).code).toBe("install_blocked");
    expect(existsSync(f.target)).toBe(false);
    // A process list that can't be read never lets the install through.
    f.running.mo2 = null;
    expect((await f.host.plan("first")).blocked).toBe("XF Studio couldn't check whether Mod Organizer 2 is open. Close it if it is, then choose Check again.");
    expect((await refusal(() => f.host.install("first", plan.token))).code).toBe("install_blocked");
    f.setRunning(false);
    // Closing MO2 doesn't change what was reviewed: the same consent now installs.
    expect((await f.host.install("first", plan.token)).route).toBe("mo2");
  } finally { f.cleanup(); }
});

test("consent is to the reviewed plan: a changed mod list, settings, placement or earlier install needs a new review (INSTALL-07)", async () => {
  const f = fixture("mo2");
  try {
    f.candidate("first", "one");
    const plan = await f.host.plan("first");
    writeFileSync(f.modlistFile, MODLIST + "+New Mod\r\n");
    expect(await refusal(() => f.host.install("first", plan.token))).toMatchObject({ code: "stale_plan" });
    expect(existsSync(f.target)).toBe(false);
    expect(readFileSync(f.modlistFile, "utf8")).toBe(MODLIST + "+New Mod\r\n");
    const again = await f.host.plan("first");
    f.settings.revision = 4;
    expect((await refusal(() => f.host.install("first", again.token))).code).toBe("stale_plan");
    // The same list, but the frameworks found in it changed, so the row would go to another section than the one reviewed.
    const reviewed = await f.host.plan("first");
    f.setFrameworks(["ArchiveXL", "TweakXL", "Neon Lashes"]);
    expect((await f.host.plan("first")).changes[1]).not.toBe(reviewed.changes[1]);
    expect((await refusal(() => f.host.install("first", reviewed.token))).code).toBe("stale_plan");
    expect(existsSync(f.target)).toBe(false);
  } finally { f.cleanup(); }
});

test("an update replaces only XF Studio's own earlier files and leaves the list as it is", async () => {
  const f = fixture("mo2");
  try {
    f.candidate("first", "one"); f.candidate("second", "two");
    await f.host.install("first", (await f.host.plan("first")).token);
    const listed = readFileSync(f.modlistFile, "utf8");
    const plan = await f.host.plan("second");
    expect(plan.replacing).toBe(true);
    expect(plan.changes[0]).toBe(`Replace the 2 files of the mod “${MOD}” that XF Studio added before, in ${f.target}.`);
    expect(plan.changes[1]).toBe(`“${MOD}” is already switched on in the profile “Main (2026)”; it stays where it is.`);
    await f.host.install("second", plan.token);
    expect(readFileSync(join(f.target, "xfs_test.archive"), "utf8")).toBe("two-0");
    expect(readFileSync(f.modlistFile, "utf8")).toBe(listed);
  } finally { f.cleanup(); }
});

test("direct: the game folder route names the folder, refuses files it didn't put there, and never touches MO2", async () => {
  const f = fixture("direct");
  try {
    f.candidate("first", "one");
    mkdirSync(f.target, { recursive: true });
    writeFileSync(join(f.target, "other.archive"), "another mod");
    const plan = await f.host.plan("first");
    expect(plan).toMatchObject({ route: "direct", place: "your game folder", blocked: null });
    expect(plan.changes).toEqual([`Copy 2 files into your game's mod folder: ${f.target}.`]);
    await f.host.install("first", plan.token);
    expect(readdirSync(f.target).sort()).toEqual(["other.archive", "xfs_test.archive", "xfs_test.archive.xl"]);
    expect(readFileSync(f.modlistFile, "utf8")).toBe(MODLIST);
  } finally { f.cleanup(); }
  const g = fixture("direct");
  try {
    g.candidate("first", "one");
    mkdirSync(g.target, { recursive: true });
    writeFileSync(join(g.target, "xfs_test.archive"), "someone else's file");
    expect((await g.host.plan("first")).blocked).toContain("that XF Studio didn't put there, so nothing was added");
    expect(readFileSync(join(g.target, "xfs_test.archive"), "utf8")).toBe("someone else's file");
  } finally { g.cleanup(); }
});

test("part of the mod already installed elsewhere blocks the install; missing setup and builds say the next step", async () => {
  const xl = "customizations:\n  female: base\\characters\\xfs_eye.inkcc\n";
  const f = fixture("mo2", MODLIST + "+Copy By Hand\r\n");
  try {
    f.candidate("first", "one", xl);
    mkdirSync(join(f.mo2, "mods", "Copy By Hand", "archive", "pc", "mod"), { recursive: true });
    writeFileSync(join(f.mo2, "mods", "Copy By Hand", "archive", "pc", "mod", "old.archive.xl"), xl);
    expect(await f.host.plan("first")).toMatchObject({ next: "retry", blocked: "Part of this mod is already installed as the Mod Organizer 2 mod “Copy By Hand”. " +
      "Switch it off in the profile “Main (2026)” in Mod Organizer 2, or remove it. Then choose Check again." });
    expect((await refusal(() => f.host.plan("../first"))).code).toBe("candidate_missing");
    expect((await refusal(() => f.host.plan("gone"))).message).toBe("This build's files are no longer there, or were changed. Build your mod again.");
    f.settings.mo2ProfileId = null;
    expect(await f.host.plan("first")).toMatchObject({ blocked: "Choose your Mod Organizer 2 instance and profile in Game & tools first.", next: "setup" });
    f.settings.gameRoot = null;
    expect(await f.host.plan("first")).toMatchObject({ blocked: "Choose your Cyberpunk 2077 folder in Game & tools first.", next: "setup" });
  } finally { f.cleanup(); }
});

test("only what the game would load counts as a duplicate, with advice that works where it is (INSTALL-06, UI-100)", async () => {
  const xl = "customizations:\n  female: base\\characters\\xfs_eye.inkcc\n";
  const put = (folder: string, name = "old.archive.xl") => { mkdirSync(folder, { recursive: true }); writeFileSync(join(folder, name), xl); };
  // A switched-off copy, or one MO2 doesn't list, is not loaded: it never blocks.
  const f = fixture("mo2", MODLIST.replace("-Old Hair", "-Old Copy"));
  try {
    f.candidate("first", "one", xl);
    put(join(f.mo2, "mods", "Old Copy", "archive", "pc", "mod"));
    put(join(f.mo2, "mods", "Not Listed", "archive", "pc", "mod"));
    expect((await f.host.plan("first")).blocked).toBeNull();
    // MO2's Overwrite is always loaded.
    put(join(f.mo2, "overwrite", "archive", "pc", "mod"), "stray.archive.xl");
    expect((await f.host.plan("first")).blocked).toBe("Part of this mod is already installed as Mod Organizer 2's Overwrite folder. " +
      "Move “stray.archive.xl” out of Overwrite in Mod Organizer 2, or delete it. Then choose Check again.");
  } finally { f.cleanup(); }
  // In the game folder: a copy Vortex deployed is changed in Vortex; one copied by hand is removed.
  const g = fixture("direct");
  try {
    g.candidate("first", "one", xl);
    put(g.target, "vortex.archive.xl");
    const deployed = statSync(join(g.target, "vortex.archive.xl")).mtimeMs;
    writeFileSync(join(g.game, "vortex.deployment.json"), JSON.stringify({ version: 1, instance: "x", deploymentMethod: "hardlink_activator",
      files: [{ relPath: "archive\\pc\\mod\\vortex.archive.xl", source: "Eye Looks-123-1-0", time: deployed }] }));
    expect((await g.host.plan("first")).blocked).toBe("Part of this mod is already installed as the Vortex mod “Eye Looks-123-1-0”. " +
      "Disable or remove it in Vortex and deploy. Then choose Check again.");
    rmSync(join(g.game, "vortex.deployment.json"));
    expect((await g.host.plan("first")).blocked).toBe("Part of this mod is already installed as your game's archive\\pc\\mod folder (“vortex.archive.xl”). " +
      "Remove that mod's files from the game folder. Then choose Check again.");
    // XF Studio's own file there is not a duplicate of itself.
    rmSync(join(g.target, "vortex.archive.xl"));
    await g.host.install("first", (await g.host.plan("first")).token);
    expect((await g.host.plan("first")).blocked).toBeNull();
  } finally { g.cleanup(); }
});

test("files Vortex deployed are never to be renamed: the refusal says to change them in Vortex (UI-100)", async () => {
  const f = fixture("direct");
  try {
    f.candidate("first", "one");
    mkdirSync(f.target, { recursive: true });
    writeFileSync(join(f.target, "xfs_test.archive"), "a Vortex mod's file");
    writeFileSync(join(f.game, "vortex.deployment.json"), JSON.stringify({ version: 1, instance: "x",
      files: [{ relPath: "archive\\pc\\mod\\xfs_test.archive", source: "Old XF Looks-1-0", time: statSync(join(f.target, "xfs_test.archive")).mtimeMs }] }));
    const plan = await f.host.plan("first");
    expect(plan.next).toBe("rename");
    expect(plan.blocked).toBe(`Vortex has already put a file named like “${MOD}”'s into your game folder (the Vortex mod “Old XF Looks-1-0”), so nothing ` +
      "was added. Remove or disable that mod in Vortex and deploy, or rename your mod in Mod package, then try again.");
    expect(plan.blocked).not.toContain("Remove or rename those files");
  } finally { f.cleanup(); }
});

test("the legacy diagnostic folder is refused in plain words with its one action (UI-100)", async () => {
  const f = fixture("mo2", MODLIST + "+XF Studio\r\n");
  try {
    f.candidate("first", "one");
    mkdirSync(join(f.mo2, "mods", "XF Studio"));
    expect(await f.host.plan("first")).toMatchObject({ next: "retry", blocked: "Mod Organizer 2 still has an early test copy of this mod: the mod “XF Studio”. " +
      "Remove that mod in Mod Organizer 2 (right-click it, then Remove mod), then choose Check again." });
  } finally { f.cleanup(); }
});

test("a mod name MO2 reads as a separator is a rename step, not a failure (INSTALL-11)", async () => {
  const f = fixture("mo2");
  try {
    f.candidate("sep", "one", undefined, "Looks_separator");
    expect(await f.host.plan("sep")).toMatchObject({ next: "rename", blocked: "Mod Organizer 2 treats a name ending in “_separator” as a section heading, " +
      "so “Looks_separator” can't be a mod's name there. Rename it in Mod package, then build it again." });
    const handler = createModInstallHandler(() => f.host);
    const answer = await handler(new Request("http://127.0.0.1:4400/api/mod-install", { method: "POST",
      headers: { "Content-Type": "application/json", Origin: "http://127.0.0.1:4400" }, body: JSON.stringify({ action: "plan", candidateId: "sep" }) }));
    expect(answer.status).toBe(200);
  } finally { f.cleanup(); }
});

/** The journal a real update leaves when it is interrupted after `done` of its two renames (the game holding the old `.archive`). */
function interrupt(f: ReturnType<typeof fixture>, next: string, done: 0 | 1 | 2) {
  const name = readdirSync(f.receipts).find(file => /^[a-f0-9]{24}\.json$/.test(file))!;
  const prior = JSON.parse(readFileSync(join(f.receipts, name), "utf8"));
  const backup = join(f.receipts, `${prior.targetId}-test-backup-${next}`); mkdirSync(backup);
  for (const entry of prior.files) writeFileSync(join(backup, entry.path.split("/").at(-1)), readFileSync(join(f.target, entry.path.split("/").at(-1))));
  const files = JSON.parse(readFileSync(join(f.store, next, "manifest.json"), "utf8")).files as { path: string }[];
  const pending = { ...prior, candidateId: next, files, installedAt: new Date().toISOString(), rollback: { prior: { ...prior, rollback: null }, backup } };
  writeFileSync(join(f.receipts, `${prior.targetId}.journal.json`), JSON.stringify({ schema: "xfs/install-journal-1", targetId: prior.targetId,
    target: prior.target, names: files.map(x => x.path.split("/").at(-1)), next: files, prior, backup, pending }));
  for (const entry of files.slice(0, done)) writeFileSync(join(f.target, entry.path.split("/").at(-1)!), readFileSync(join(f.store, next, ...entry.path.split("/"))));
}

test("an interrupted install is finished or undone on the next plan, once the game is closed (INSTALL-02)", async () => {
  const f = fixture("direct");
  try {
    f.candidate("first", "one"); f.candidate("second", "two");
    await f.host.install("first", (await f.host.plan("first")).token);
    interrupt(f, "second", 1);
    // The game still holds the file: nothing is touched, and the plan says to close it.
    f.running.game = true;
    const waiting = await f.host.plan("second");
    expect(waiting).toMatchObject({ next: "retry", blocked: `Cyberpunk 2077 is running, and an earlier install of “${MOD}” needs finishing. Close the game, then choose Check again.` });
    expect(readdirSync(f.receipts).some(name => name.endsWith(".journal.json"))).toBe(true);
    f.running.game = false;
    const plan = await f.host.plan("second");
    expect(plan.notes[0]).toBe(`An earlier install of “${MOD}” was interrupted; XF Studio has put back the copy from before it.`);
    expect(plan).toMatchObject({ blocked: null, replacing: true });
    expect(readFileSync(join(f.target, "xfs_test.archive"), "utf8")).toBe("one-0");
    await f.host.install("second", plan.token);
    expect(readFileSync(join(f.target, "xfs_test.archive"), "utf8")).toBe("two-0");
    // All new files already in place: the install is finished instead.
    f.candidate("third", "three");
    interrupt(f, "third", 2);
    expect((await f.host.plan("third")).notes[0]).toBe(`An earlier install of “${MOD}” was interrupted; XF Studio has finished it.`);
    expect(readFileSync(join(f.target, "xfs_test.archive"), "utf8")).toBe("three-0");
  } finally { f.cleanup(); }
});

test("replacing an .archive waits while the game runs (it holds the file open), and when that can't be told (INSTALL-02, INSTALL-10)", async () => {
  const f = fixture("direct");
  try {
    f.candidate("first", "one"); f.candidate("second", "two");
    f.running.game = true;
    // A first install replaces nothing, so a running game doesn't stop it.
    await f.host.install("first", (await f.host.plan("first")).token);
    const plan = await f.host.plan("second");
    expect(plan.blocked).toBe("Cyberpunk 2077 is running. Close the game, then choose Check again. Windows won't let XF Studio replace a mod file the game is using.");
    f.running.game = null;
    expect((await f.host.plan("second")).blocked).toBe("XF Studio couldn't check whether Cyberpunk 2077 is running. Close the game if it is, then choose Check again.");
    expect((await refusal(() => f.host.install("second", plan.token))).code).toBe("install_blocked");
    expect(readFileSync(join(f.target, "xfs_test.archive"), "utf8")).toBe("one-0");
  } finally { f.cleanup(); }
});

test("a mod removed in MO2, or whose files were deleted, is offered as a fresh install (INSTALL-03)", async () => {
  const f = fixture("mo2");
  try {
    f.candidate("first", "one"); f.candidate("second", "two");
    await f.host.install("first", (await f.host.plan("first")).token);
    // MO2's Remove mod deletes the folder and the row.
    rmSync(join(f.mo2, "mods", MOD), { recursive: true });
    writeFileSync(f.modlistFile, MODLIST);
    const plan = await f.host.plan("second");
    expect(plan).toMatchObject({ blocked: null, replacing: false });
    expect(plan.notes).toContain(`“${MOD}” was removed after XF Studio added it, so it is added again as new.`);
    await f.host.install("second", plan.token);
    expect(f.lines()[1]).toBe(`+${MOD}`);
    expect(readFileSync(join(f.target, "xfs_test.archive"), "utf8")).toBe("two-0");
  } finally { f.cleanup(); }
  const g = fixture("direct");
  try {
    g.candidate("first", "one"); g.candidate("second", "two");
    await g.host.install("first", (await g.host.plan("first")).token);
    for (const name of ["xfs_test.archive", "xfs_test.archive.xl"]) rmSync(join(g.target, name));
    expect(await g.host.plan("second")).toMatchObject({ blocked: null, replacing: false });
    // A file of that name someone else put there since still refuses.
    writeFileSync(join(g.target, "xfs_test.archive"), "someone else's");
    expect((await g.host.plan("second")).blocked).toContain("didn't put there");
  } finally { g.cleanup(); }
});

test("install ownership is per user on this computer: another host's install is its own, and an earlier folder's record is taken over (INSTALL-04)", async () => {
  // Localhost and the desktop app share one receipts folder: each sees the other's install as XF Studio's.
  const f = fixture("mo2");
  try {
    f.candidate("first", "one"); f.candidate("second", "two");
    await f.host.install("first", (await f.host.plan("first")).token);
    const other = f.make(f.receipts, []);
    expect(await other.plan("second")).toMatchObject({ blocked: null, replacing: true });
  } finally { f.cleanup(); }
  // An install recorded in a host's own earlier receipts folder is adopted by the shared one.
  const g = fixture("mo2", MODLIST, { receipts: "shared", legacy: ["localhost-data"] });
  try {
    g.candidate("first", "one"); g.candidate("second", "two");
    const old = g.make(join(g.root, "localhost-data"), []);
    await old.install("first", (await old.plan("first")).token);
    const plan = await g.host.plan("second");
    expect(plan).toMatchObject({ blocked: null, replacing: true });
    expect(readdirSync(join(g.root, "localhost-data")).some(name => name.includes(".json.adopted-"))).toBe(true);
    await g.host.install("second", plan.token);
    expect(readFileSync(join(g.target, "xfs_test.archive"), "utf8")).toBe("two-0");
  } finally { g.cleanup(); }
});

test("modlist.txt is written back byte for byte: its encoding, line endings and trailing spaces (INSTALL-05)", async () => {
  // An ANSI row (as an older MO2 or an editor leaves it), LF and CRLF rows, trailing spaces, no final line ending.
  const ansi = Buffer.concat([Buffer.from("# gen\r\n+Caf"), Buffer.from([0xe9]), Buffer.from(" Mod\n-Old  \r\n+Looks_separator")]);
  const f = fixture("mo2", ansi, { ansi: 1252 });
  try {
    f.candidate("first", "one");
    await f.host.install("first", (await f.host.plan("first")).token);
    expect(readFileSync(f.modlistFile)).toEqual(Buffer.concat([Buffer.from(`# gen\r\n+${MOD}\n+Caf`), Buffer.from([0xe9]), Buffer.from(" Mod\n-Old  \r\n+Looks_separator")]));
  } finally { f.cleanup(); }
  // Without a code page it can read back exactly, the list is never changed, and the plan says how to fix it.
  const g = fixture("mo2", ansi, { ansi: null });
  try {
    g.candidate("first", "one");
    const plan = await g.host.plan("first");
    expect(plan.blocked).toBe("The mod list of the profile “Main (2026)” is saved in a text format XF Studio can't edit without changing other rows, so " +
      "nothing was changed. Open Mod Organizer 2, switch any mod off and on again so it saves the list, close it, then choose Check again.");
    expect(readFileSync(g.modlistFile)).toEqual(ansi);
    expect(existsSync(g.target)).toBe(false);
  } finally { g.cleanup(); }
  const bom = Buffer.concat([Buffer.from([0xef, 0xbb, 0xbf]), Buffer.from(`+Neon Lashes  \n-${MOD}\r\n+Looks_separator`)]);
  const h = fixture("mo2", bom);
  try {
    h.candidate("first", "one");
    await h.host.install("first", (await h.host.plan("first")).token);
    expect(readFileSync(h.modlistFile)).toEqual(Buffer.concat([Buffer.from([0xef, 0xbb, 0xbf]), Buffer.from(`+Neon Lashes  \n+${MOD}\r\n+Looks_separator`)]));
  } finally { h.cleanup(); }
});

test("a mod list XF Studio can't write is found before any file is copied, in plain words (INSTALL-08)", async () => {
  const f = fixture("mo2");
  try {
    f.candidate("first", "one");
    const plan = await f.host.plan("first");
    chmodSync(f.modlistFile, 0o444);
    // Read-only after the review: the install stops before copying anything.
    expect((await refusal(() => f.host.install("first", plan.token))).code).toBe("install_blocked");
    expect(existsSync(join(f.mo2, "mods", MOD))).toBe(false);
    expect((await f.host.plan("first")).blocked).toContain("is read-only, so XF Studio can't add to it.");
    chmodSync(f.modlistFile, 0o644);
    // Linked to another file: replacing it would split the two.
    linkSync(f.modlistFile, join(f.root, "linked-modlist.txt"));
    expect((await f.host.plan("first")).blocked).toContain("is linked to another file, so XF Studio won't change it.");
    rmSync(join(f.root, "linked-modlist.txt"));
    rmSync(f.modlistFile);
    expect((await f.host.plan("first")).blocked).toBe("The profile “Main (2026)” has no mod list yet. Open Mod Organizer 2 with that profile once and close it, then choose Check again.");
    expect(readdirSync(join(f.mo2, "profiles", "Main (2026)"))).toEqual([]);
  } finally { try { chmodSync(f.modlistFile, 0o644); } catch { /* removed */ } f.cleanup(); }
});

test("a verification workspace or test server never writes: its plan is read only and says why (INSTALL-01)", async () => {
  const f = fixture("mo2", MODLIST, { readOnly: READ_ONLY_VERIFICATION });
  try {
    f.candidate("first", "one");
    const before = { mods: tree(join(f.mo2, "mods")), profiles: tree(join(f.mo2, "profiles")), game: tree(f.game), list: readFileSync(f.modlistFile) };
    const plan = await f.host.plan("first");
    // The plan still reads (so a test sees the real review), but it can't be accepted and offers no button.
    expect(plan).toMatchObject({ blocked: READ_ONLY_VERIFICATION, next: null });
    expect(plan.changes[1]).toContain("At the bottom of the \"Looks\" section");
    expect(await refusal(() => f.host.install("first", plan.token))).toMatchObject({ code: "install_unavailable", message: READ_ONLY_VERIFICATION });
    expect({ mods: tree(join(f.mo2, "mods")), profiles: tree(join(f.mo2, "profiles")), game: tree(f.game), list: readFileSync(f.modlistFile) }).toEqual(before);
  } finally { f.cleanup(); }
  // An interrupted install is left for a normal session: a test copy never recovers it.
  const g = fixture("direct");
  try {
    g.candidate("first", "one"); g.candidate("second", "two");
    await g.host.install("first", (await g.host.plan("first")).token);
    interrupt(g, "second", 1);
    const readOnly = new ModInstallHost({ candidateStore: g.store, receiptsRoot: g.receipts, settings: () => g.settings, readOnly: READ_ONLY_VERIFICATION });
    expect((await readOnly.plan("second")).blocked).toBe(READ_ONLY_VERIFICATION);
    expect(readFileSync(join(g.target, "xfs_test.archive"), "utf8")).toBe("two-0");
    expect(readdirSync(g.receipts).some(name => name.endsWith(".journal.json"))).toBe(true);
  } finally { g.cleanup(); }
});

test("refusals map to plain words and a structured next step (UI-99)", () => {
  expect(installIssue(Error("Linked path is not an install destination: X"), MOD).next).toBe("setup");
  expect(installIssue(Error("Install failed; recover the pending transaction before retrying: EBUSY"), MOD)).toEqual({ next: "retry",
    text: "An earlier install was interrupted before it finished. XF Studio finishes or undoes it when you check again: close the game if it's running, then choose Check again." });
  expect(installIssue(Error("anything else"), MOD).text).toBe("XF Studio couldn't add this mod safely, so nothing was changed. Try again, or report the problem from Help.");
});

test("the process check reads MO2 and the game in one bounded tasklist run", async () => {
  const apps = await windowsRunningApps();
  if (process.platform === "win32") for (const value of [apps.mo2, apps.game]) expect(typeof value === "boolean" || value === null).toBe(true);
  else expect(apps).toEqual({ mo2: false, game: false });
});

test("Show in folder opens the build's archive folder; the endpoint takes only a candidate ID from the page", async () => {
  const f = fixture("mo2");
  try {
    f.candidate("first", "one");
    f.host.reveal("first");
    expect(f.revealed).toEqual([join(f.store, "first", "archive")]);
    const handler = createModInstallHandler(() => f.host);
    const post = (body: unknown, origin = "http://127.0.0.1:4400") => handler(new Request("http://127.0.0.1:4400/api/mod-install", {
      method: "POST", headers: { "Content-Type": "application/json", Origin: origin }, body: JSON.stringify(body) }));
    expect((await post({ action: "plan", candidateId: "first" }, "http://evil.test")).status).toBe(403);
    expect((await post({ action: "plan", candidateId: "first", path: "C:\\" })).status).toBe(400);
    expect((await post({ action: "install", candidateId: "first" })).status).toBe(400);
    const plan = await (await post({ action: "plan", candidateId: "first" })).json();
    expect(plan.schema).toBe("xfs/mod-install-plan-1");
    const stale = await post({ action: "install", candidateId: "first", token: "0".repeat(64) });
    expect(stale.status).toBe(409);
    expect((await stale.json()).code).toBe("stale_plan");
    const done = await post({ action: "install", candidateId: "first", token: plan.token });
    expect((await done.json()).schema).toBe("xfs/mod-install-result-1");
    expect((await (await post({ action: "reveal", candidateId: "first" })).json())).toEqual({ ok: true });
  } finally { f.cleanup(); }
});
