// "Add to my mod manager" (UI-82) over a fake MO2 tree and game folder: the plan names exactly what changes and where, the one
// mod-list row lands in the right separator section (the file is the reverse of MO2's pane), consent is to that plan only, and
// every refusal (a folder or files XF Studio didn't make, MO2 open, a changed list, a duplicate elsewhere) changes nothing.
import { expect, test } from "bun:test";
import { createHash } from "node:crypto";
import { existsSync, mkdirSync, mkdtempSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { defaultLocalSettings, type LocalSettings } from "../src/local-settings";
import { createModInstallHandler, ModInstallError, ModInstallHost } from "../src/mod-install-host";
import { EYE_MAKEUP_MOD } from "../src/mod-branding";

const digest = (body: string) => createHash("sha256").update(body).digest("hex");
const MOD = EYE_MAKEUP_MOD.modName;
/** A profile of three sections, frameworks at the bottom of the pane (the last rows of the file). */
const MODLIST = [
  "# This file was automatically generated by Mod Organizer.",
  "+Neon Lashes",
  "-Old Hair",
  "+Looks_separator",
  "+Better Lighting",
  "+Visuals_separator",
  "+ArchiveXL",
  "+TweakXL",
  "+CORE, LIBS, FRAMEWORKS_separator",
].join("\r\n") + "\r\n";

function fixture(route: "direct" | "mo2", modlist = MODLIST) {
  const root = mkdtempSync(join(tmpdir(), "xfs-mod-install-"));
  const game = join(root, "game"), mo2 = join(root, "mo2"), store = join(root, "candidates"), receipts = join(root, "receipts");
  const profile = "Main (2026)";
  mkdirSync(join(game, "bin", "x64"), { recursive: true });
  mkdirSync(join(game, "archive", "pc"), { recursive: true });
  writeFileSync(join(game, "bin", "x64", "Cyberpunk2077.exe"), "fixture");
  mkdirSync(join(mo2, "mods", "Neon Lashes"), { recursive: true });
  mkdirSync(join(mo2, "profiles", profile), { recursive: true });
  const modlistFile = join(mo2, "profiles", profile, "modlist.txt");
  writeFileSync(modlistFile, modlist);
  mkdirSync(store);
  const settings: LocalSettings = { ...defaultLocalSettings(), revision: 3, gameRoot: game, mo2Root: mo2, mo2ProfileId: profile, launchRoute: route };
  let running = false;
  const revealed: string[] = [];
  const host = new ModInstallHost({ candidateStore: store, receiptsRoot: receipts, settings: () => settings,
    mo2Running: () => running, frameworkMods: () => ["ArchiveXL", "TweakXL"], reveal: path => { revealed.push(path); return true; } });
  const target = route === "direct" ? join(game, "archive", "pc", "mod") : join(mo2, "mods", MOD, "archive", "pc", "mod");
  function candidate(id: string, version: string, xl = `${version}-1`) {
    const folder = join(store, id), payload = join(folder, "archive", "pc", "mod");
    mkdirSync(payload, { recursive: true });
    const files = ["xfs_test.archive", "xfs_test.archive.xl"].map((name, index) => {
      const body = index ? xl : `${version}-0`;
      writeFileSync(join(payload, name), body);
      return { path: `archive/pc/mod/${name}`, sha256: digest(body), bytes: Buffer.byteLength(body) };
    });
    writeFileSync(join(folder, "manifest.json"), JSON.stringify({ schema: "xfs/local-package-1", namespace: "xfs_test",
      verifiedUnpackedFiles: 2, installed: false, gameRenderingVerified: false, files }));
  }
  const lines = () => readFileSync(modlistFile, "utf8").split("\r\n");
  return { root, game, mo2, store, receipts, settings, host, target, candidate, modlistFile, lines, revealed,
    setRunning: (on: boolean) => { running = on; }, cleanup: () => rmSync(root, { recursive: true, force: true }) };
}
const refusal = (run: () => unknown) => { try { run(); } catch (error) { return error as ModInstallError; } throw Error("Expected a refusal."); };

test("MO2: the plan names the mod, its folder and the one mod-list row, then install adds exactly that", () => {
  const f = fixture("mo2");
  try {
    f.candidate("first", "one");
    const plan = f.host.plan("first");
    expect(plan).toMatchObject({ route: "mo2", modName: MOD, place: "Mod Organizer 2 (profile “Main (2026)”)", blocked: null, replacing: false });
    expect(plan.changes[0]).toBe(`Add the mod “${MOD}” to Mod Organizer 2, with its 2 files in ${f.target}.`);
    // The pane shows the file reversed: the new row goes at the bottom of the first section that holds no frameworks ("Looks").
    expect(plan.changes[1]).toBe(`Add “${MOD}” to the profile “Main (2026)”, switched on. At the bottom of the "Looks" section, where Mod Organizer puts newly installed mods.`);
    expect(plan.changes[2]).toBe("Nothing else in your mod list changes.");
    const before = f.lines();
    const result = f.host.install("first", plan.token);
    expect(result.message).toContain("switched on in the profile “Main (2026)”");
    expect(readdirSync(f.target).sort()).toEqual(["xfs_test.archive", "xfs_test.archive.xl"]);
    // One row added, directly after the comment (the bottom of the "Looks" section in the pane); nothing else moved.
    expect(f.lines()).toEqual([before[0], `+${MOD}`, ...before.slice(1)]);
    expect(readdirSync(join(f.receipts, "modlists"))).toHaveLength(1);
    expect(readdirSync(join(f.mo2, "profiles", "Main (2026)")).sort()).toEqual(["modlist.txt"]);
  } finally { f.cleanup(); }
});

test("MO2: a profile whose every section holds frameworks gets MO2's own default place, and a related entry is followed", () => {
  const f = fixture("mo2", "+ArchiveXL\n+Frameworks_separator\n");
  try {
    f.candidate("first", "one");
    const plan = f.host.plan("first");
    expect(plan.changes[1]).toContain("Every section in this profile holds frameworks");
    f.host.install("first", plan.token);
    expect(readFileSync(f.modlistFile, "utf8")).toBe(`+${MOD}\n+ArchiveXL\n+Frameworks_separator\n`);
  } finally { f.cleanup(); }
  const g = fixture("mo2", `+Better Lighting\n+${EYE_MAKEUP_MOD.predecessorMods[0]}\n+Looks_separator\n`);
  try {
    g.candidate("first", "one");
    const plan = g.host.plan("first");
    expect(plan.changes[1]).toContain(`Directly below "${EYE_MAKEUP_MOD.predecessorMods[0]}"`);
    // The older mod is named for the person to decide; it is never switched off for them.
    expect(plan.notes[0]).toContain(`“${EYE_MAKEUP_MOD.predecessorMods[0]}” is also switched on`);
    g.host.install("first", plan.token);
    expect(readFileSync(g.modlistFile, "utf8")).toBe(`+Better Lighting\n+${MOD}\n+${EYE_MAKEUP_MOD.predecessorMods[0]}\n+Looks_separator\n`);
  } finally { g.cleanup(); }
});

test("MO2: a listed but switched-off entry is switched on where it is", () => {
  const f = fixture("mo2", `+Neon Lashes\n-${MOD}\n+Looks_separator\n`);
  try {
    f.candidate("first", "one");
    const plan = f.host.plan("first");
    expect(plan.changes[1]).toBe(`“${MOD}” is already in the profile “Main (2026)”; switch it on where it is.`);
    f.host.install("first", plan.token);
    expect(readFileSync(f.modlistFile, "utf8")).toBe(`+Neon Lashes\n+${MOD}\n+Looks_separator\n`);
  } finally { f.cleanup(); }
});

test("MO2: a folder of that name XF Studio didn't create is refused, and nothing changes", () => {
  const f = fixture("mo2");
  try {
    f.candidate("first", "one");
    mkdirSync(join(f.mo2, "mods", MOD), { recursive: true });
    writeFileSync(join(f.mo2, "mods", MOD, "readme.txt"), "someone else's mod");
    const plan = f.host.plan("first");
    expect(plan.blocked).toContain("that XF Studio didn't put there");
    expect(refusal(() => f.host.install("first", plan.token))).toMatchObject({ code: "install_blocked" });
    expect(readFileSync(f.modlistFile, "utf8")).toBe(MODLIST);
    expect(readdirSync(join(f.mo2, "mods", MOD))).toEqual(["readme.txt"]);
  } finally { f.cleanup(); }
});

test("MO2: while Mod Organizer 2 is open the install waits, with the one next step", () => {
  const f = fixture("mo2");
  try {
    f.candidate("first", "one");
    f.setRunning(true);
    const plan = f.host.plan("first");
    expect(plan.blocked).toBe("Mod Organizer 2 is open. Close it first, then try again: it rewrites its mod list when it closes, and would undo this.");
    expect(refusal(() => f.host.install("first", plan.token)).code).toBe("install_blocked");
    expect(existsSync(f.target)).toBe(false);
    f.setRunning(false);
    // Closing MO2 doesn't change what was reviewed: the same consent now installs.
    expect(f.host.install("first", plan.token).route).toBe("mo2");
  } finally { f.cleanup(); }
});

test("consent is to the reviewed plan: a changed mod list, settings or earlier install needs a new review", () => {
  const f = fixture("mo2");
  try {
    f.candidate("first", "one");
    const plan = f.host.plan("first");
    writeFileSync(f.modlistFile, MODLIST + "+New Mod\r\n");
    expect(refusal(() => f.host.install("first", plan.token))).toMatchObject({ code: "stale_plan" });
    expect(existsSync(f.target)).toBe(false);
    expect(readFileSync(f.modlistFile, "utf8")).toBe(MODLIST + "+New Mod\r\n");
    const again = f.host.plan("first");
    f.settings.revision = 4;
    expect(refusal(() => f.host.install("first", again.token)).code).toBe("stale_plan");
  } finally { f.cleanup(); }
});

test("an update replaces only XF Studio's own earlier files and leaves the list as it is", () => {
  const f = fixture("mo2");
  try {
    f.candidate("first", "one"); f.candidate("second", "two");
    f.host.install("first", f.host.plan("first").token);
    const listed = readFileSync(f.modlistFile, "utf8");
    const plan = f.host.plan("second");
    expect(plan.replacing).toBe(true);
    expect(plan.changes[0]).toBe(`Replace the 2 files of the mod “${MOD}” that XF Studio added before, in ${f.target}.`);
    expect(plan.changes[1]).toBe(`“${MOD}” is already switched on in the profile “Main (2026)”; it stays where it is.`);
    f.host.install("second", plan.token);
    expect(readFileSync(join(f.target, "xfs_test.archive"), "utf8")).toBe("two-0");
    expect(readFileSync(f.modlistFile, "utf8")).toBe(listed);
  } finally { f.cleanup(); }
});

test("direct: the game folder route names the folder, refuses files it didn't put there, and never touches MO2", () => {
  const f = fixture("direct");
  try {
    f.candidate("first", "one");
    mkdirSync(f.target, { recursive: true });
    writeFileSync(join(f.target, "other.archive"), "another mod");
    const plan = f.host.plan("first");
    expect(plan).toMatchObject({ route: "direct", place: "your game folder", blocked: null });
    expect(plan.changes).toEqual([`Copy 2 files into your game's mod folder: ${f.target}.`]);
    f.host.install("first", plan.token);
    expect(readdirSync(f.target).sort()).toEqual(["other.archive", "xfs_test.archive", "xfs_test.archive.xl"]);
    expect(readFileSync(f.modlistFile, "utf8")).toBe(MODLIST);
  } finally { f.cleanup(); }
  const g = fixture("direct");
  try {
    g.candidate("first", "one");
    mkdirSync(g.target, { recursive: true });
    writeFileSync(join(g.target, "xfs_test.archive"), "someone else's file");
    expect(g.host.plan("first").blocked).toContain("that XF Studio didn't put there, so nothing was added");
    expect(readFileSync(join(g.target, "xfs_test.archive"), "utf8")).toBe("someone else's file");
  } finally { g.cleanup(); }
});

test("part of the mod already installed elsewhere blocks the install; missing setup and builds say the next step", () => {
  const xl = "customizations:\n  female: base\\characters\\xfs_eye.inkcc\n";
  const f = fixture("mo2");
  try {
    f.candidate("first", "one", xl);
    mkdirSync(join(f.mo2, "mods", "Copy By Hand", "archive", "pc", "mod"), { recursive: true });
    writeFileSync(join(f.mo2, "mods", "Copy By Hand", "archive", "pc", "mod", "old.archive.xl"), xl);
    expect(f.host.plan("first").blocked).toBe("Part of this mod is already installed in the Mod Organizer 2 mod “Copy By Hand”. Remove or switch that off first, then try again.");
    expect(refusal(() => f.host.plan("../first")).code).toBe("candidate_missing");
    expect(refusal(() => f.host.plan("gone")).message).toBe("This build's files are no longer there, or were changed. Build your mod again.");
    f.settings.mo2ProfileId = null;
    expect(f.host.plan("first").blocked).toBe("Choose your Mod Organizer 2 instance and profile in Game & tools first.");
    f.settings.gameRoot = null;
    expect(f.host.plan("first").blocked).toBe("Choose your Cyberpunk 2077 folder in Game & tools first.");
  } finally { f.cleanup(); }
});

test("Show in folder opens the build's archive folder; the endpoint takes only a candidate ID from the page", async () => {
  const f = fixture("mo2");
  try {
    f.candidate("first", "one");
    f.host.reveal("first");
    expect(f.revealed).toEqual([join(f.store, "first", "archive")]);
    const handler = createModInstallHandler(() => f.host);
    const post = (body: unknown, origin = "http://127.0.0.1:4400") => handler(new Request("http://127.0.0.1:4400/api/mod-install", {
      method: "POST", headers: { "Content-Type": "application/json", Origin: origin }, body: JSON.stringify(body) }));
    expect((await post({ action: "plan", candidateId: "first" }, "http://evil.test")).status).toBe(403);
    expect((await post({ action: "plan", candidateId: "first", path: "C:\\" })).status).toBe(400);
    expect((await post({ action: "install", candidateId: "first" })).status).toBe(400);
    const plan = await (await post({ action: "plan", candidateId: "first" })).json();
    expect(plan.schema).toBe("xfs/mod-install-plan-1");
    const stale = await post({ action: "install", candidateId: "first", token: "0".repeat(64) });
    expect(stale.status).toBe(409);
    expect((await stale.json()).code).toBe("stale_plan");
    const done = await post({ action: "install", candidateId: "first", token: plan.token });
    expect((await done.json()).schema).toBe("xfs/mod-install-result-1");
    expect((await (await post({ action: "reveal", candidateId: "first" })).json())).toEqual({ ok: true });
  } finally { f.cleanup(); }
});
